### ISSUE TITLE
Support for selecting mpd audio_output

### ISSUE THREAD

**Issue by nhannam** [SoongNoonien/mpdevil#12]
MPD allows configuration of multiple named audio_outputs, and the protocol supports listing / switching the active ones (https://www.musicpd.org/doc/html/protocol.html#audio-output-devices).  It would be great if mpdevil could support listing / switching audio outputs through the UI.

In my config I have one audio_output to play music through the speakers on the device mpd is running on, and a second audio_output to play music on a remote speaker.  At present I have to switch to a different mpd client to change playback device.

**Comment by SoongNoonien** [comment]
The current git version is now capable of configuring the mpd audio outputs. Just do a right click on the volume button. Please let me know if it works as expected.

**Comment by nhannam** [comment]
Yeah, that seems to work great.

I have the mixer_type set to none for the remote speaker, and that seems to work fine too - the volume control shows as disabled when the remote speaker is the active output, but can still right click to switch outputs.
(The remote speaker is actually an amplifier and I prefer to use the amp volume controls rather than clipping volume before sending to the amp).

If you have the popup open and switch output through another client, the checkboxes don't update to reflect the change.  It's not a problem as unlikely to happen and you can just close/reopen the popup to get the correct information, but thought it worth mentioning.

**Comment by SoongNoonien** [comment]
Thanks for the detailed test!

> If you have the popup open and switch output through another client, the checkboxes don't update to reflect the change. It's not a problem as unlikely to happen and you can just close/reopen the popup to get the correct information, but thought it worth mentioning.

I'm aware of that. But currently I don't have an idea of solving this elegantly so I'll leave it for now.
