### ISSUE TITLE
last.fm scrobbling

### ISSUE THREAD

**Issue by ottersarecool** [SoongNoonien/mpdevil#13]
Would be nice

**Comment by SoongNoonien** [comment]
Cause I'm not sure what exactly you are asking for I'll have to say it in general. I will neither implement any rating, suggestion or scrobbling functionality nor merge pull requests regarding such features.

Martin

PS: I would appreciate a more detailed description next time.

**Comment by ottersarecool** [comment]
well okay then, uninstalled. good day sir
