### ISSUE TITLE
Mpdevil does not show some albums

### ISSUE THREAD

**Issue by Popkornium18** [SoongNoonien/mpdevil#14]
![image](https://user-images.githubusercontent.com/46488511/99090157-8e8c9280-25ce-11eb-9b36-4ddadd040f71.png)

Here you can see ncmcpcppccdc and Mpdevil side by side and Mpdevil misses two albums from Mogwai (KIN, Every Country's Sun), that show up in ncmncppdcdn.

Curiously the Album can be found via the search in Mpdevil:
![image](https://user-images.githubusercontent.com/46488511/99090416-e925ee80-25ce-11eb-9847-134fc7f25e8c.png)

**Comment by SoongNoonien** [comment]
I'm not sure but that seems to me like an issue in the tags. Is there any output on the terminal? Could you take a screenshot of the right click popup of one of the songs form the album "KIN"?

**Comment by Popkornium18** [comment]
![image](https://user-images.githubusercontent.com/46488511/99093452-c4cc1100-25d2-11eb-885f-7789081f7cb6.png)

There is no output on the terminal from mpdevil. The songs play fine and even display the cover art.

Some more info:
Distro: Arch
MPD: 0.22.3-1
Mpdevil: 0.9.6-1

The songs are stored on a network share that is mounted with sshfs.

**Comment by SoongNoonien** [comment]
The tags look normal. To make a further analysis you can either send me such a file or I could send you a patch which will display additional information.

**Comment by Popkornium18** [comment]
Either way is fine. If I were to send you a file, how should I do it? Uploading it here might be a bad Idea because of legal shenanigans.

**Comment by SoongNoonien** [comment]
> Either way is fine.

Ok, that's good. I'd prefer if you'd send me a file.

> If I were to send you a file, how should I do it? Uploading it here might be a bad Idea because of legal shenanigans.

You can send me a private mail (`martin.wagner.dev@gmail.com`) possibly in a passworded rar archive.

**Comment by Popkornium18** [comment]
I sent you a mail.

**Comment by Popkornium18** [comment]
Interesting. No idea why GLib complains about the file, other tools like `file` seem to detect the filetype just fine.. Thanks for the quick help!
