### ISSUE TITLE
no sound with httpd stream

### ISSUE THREAD

**Issue by dln949** [SoongNoonien/mpdevil#15]
version 1.1.1 on Ubuntu 18.04.  

When streaming httpd to android using mpdroid as the client, or to the desktop ubuntu computer using a web browser as a client, I can hear the audio.  But, when I use mpdevil as the client on that same ubuntu computer, the httpd stream has no audio, the volume button is muted and I am unable to alter it.  

(mpdevil does play the MPD pulse output with no problem.)

**Comment by SoongNoonien** [comment]
With a right click on the volume button you can see which audio plugins are configured/turned on. Is the httpd plugin turned on?

> ... the volume button is muted and I am unable to alter it.

This would normally be the case when no output plugin is enabled.

**Comment by dln949** [comment]
Yes, httpd is checked, still no sound.

**Comment by SoongNoonien** [comment]
Ok, could you send me your mpd config, so I can try to reproduce the issue on my machine?

**Comment by dln949** [comment]
Sure.  How did you want that sent to you?  I don't know your email address.  

Thanks again for helping with this.

**Comment by SoongNoonien** [comment]
If don't want to post it here, my email address can be found in the AUTHORS file.

**Comment by dln949** [comment]
Ok, I sent via email to the Martin Wagner gmail address.

**Comment by dln949** [comment]
I had no audio because I misunderstood MPdevil, it on its own will not play any audio for the httpd stream.
