### ISSUE TITLE
dependency issue python3-mpd

### ISSUE THREAD

**Issue by WouterGordts** [SoongNoonien/mpdevil#16]
Thanks for the solid player!

Runs nicely on debian (mobian on the pinephone) but the .deb installer wants to install python3-mpd via apt which is not the mpd2 needed to run the application.

I fixed it by installing python-mpd2 via pip.

**Comment by SoongNoonien** [comment]
On which version of debian is mobian based? As of buster the python3-mpd package is in fact python-mp2 (>=1.0). "This is the Python 3 version of python-mpd2, a fork of the original python-mpd." (https://packages.debian.org/buster/python3-mpd). I created the .deb package with ubuntu 18.04 but I also tested it with debian 10 (buster) and it works just fine without the need of installing python-mpd2 via pip. Even `/usr/share/doc/python3-mpd/copyright` (on a debian installation) states: "Upstream-Name: python-mpd2" and "Upstream-Contact: https://github.com/Mic92/python-mpd2". Did you try to run mpdevil without the installation of python-mp2 via pip?

**Comment by WouterGordts** [comment]
I'm creating my own pinephone desktop environment based on mobian so it might be not all too standard but my /etc/issue gives **Debian GNU/Linux bullseye/sid**  and uname -a **Linux mobian 5.10-sunxi64 #2 SMP PREEMPT Tue Jan 12 09:55:56 UTC 2021 aarch64 GNU/Linux**. I'll install it again from scratch, I might have messed something up the first time around.

**Comment by WouterGordts** [comment]
Sorry about the issue, I must have messed up on the first try  because now it installs perfectly!
