### ISSUE TITLE
Feature Request: Add whole library to playlist

### ISSUE THREAD

**Issue by Popkornium18** [SoongNoonien/mpdevil#19]
Sometimes when I don't know what I want to listen to I like to add my whole library to the playlist, hit shuffle and see what comes up.
As far as I can tell that is currently not possible with mpdevil.

**Comment by SoongNoonien** [comment]
Since #18 this should be possible via a single middle click on "all artists" or via the right click menu of "all artists". But it takes a short while to display all songs in the playlist (on my setup with 5536 songs about 4s).
Please let me know if this already does what you thought of.

**Comment by Popkornium18** [comment]
Is this change included in 1.1.1?

**Comment by SoongNoonien** [comment]
No, it is currently only in master. But it will be included in the next release.

**Comment by SoongNoonien** [comment]
If you don't want to install the git version you can just download the `bin/mpdevil` file from the git repo and execute it (e.g. in your home dir).

**Comment by Popkornium18** [comment]
Yes, that works. Looking forward to the next release.
