### ISSUE TITLE
Debian/Ubuntu package

### ISSUE THREAD

**Issue by alfreetos** [SoongNoonien/mpdevil#2]
Will there be Debian packages in future releases?

**Comment by SoongNoonien** [comment]
Since I'm not using Debian/Ubuntu it's difficult to properly maintain .deb packages. Although I'd really like to see mpdevil running on other distro's than Arch and Gentoo, the development of mpdevil itself is more important for now. When mpdevil finally gets stable I might consider to provide .deb packages.

Do you need some help installing mpdevil without a package?

**Comment by alfreetos** [comment]
I am cogget a
two errors when compiling with ./autogen.sh
`checking for MPDClient installed... not found
configure: error: python module mpd not found
`
I am using pulsaudio and it works from ncmpcpp

**Comment by SoongNoonien** [comment]
You just have to install `python3-mpd`. (all python modules needed: `python3-mpd python3-bs4 python3-gobject python3-requests`)

**Comment by alfreetos** [comment]
I was unable to find `python3-gobject`. Is it `python3-gi` or `python-go`?

**Comment by alfreetos** [comment]
I installed `python3-gi` along with all other modules and it works fine now. Thanks.

**Comment by SoongNoonien** [comment]
Oh, you're right, it's `python3-gi`. I'm glad to hear it's running now. By the way, which version of Ubuntu do you use? And if you find any errors please report them to improve mpdevil.

**Comment by alfreetos** [comment]
I'm running Ubuntu 19.10 with the Budgie desktop. Can I ask are you planning to add compatibility with media keys?

**Comment by SoongNoonien** [comment]
> I'm running Ubuntu 19.10 with the Budgie desktop.

Thanks.

> Can I ask are you planning to add compatibility with media keys?

Yes, but would you mind opening a separate Issue? (btw: play/pause is already working with SPACE-key)

**Comment by SoongNoonien** [comment]
I've just published a first test .deb package with the 0.8.0 release.
