### ISSUE TITLE
Support MPD server albumart for Covers

### ISSUE THREAD

**Issue by lulis** [SoongNoonien/mpdevil#22]
Since MPD 0.21 the mpd protocol [supports albumart images](https://www.musicpd.org/doc/html/protocol.html#the-music-database).
Can mpdevil retrieve the covers by this way? 

I've first read about it on [myMPD](https://github.com/jcorporation/myMPD/wiki/Albumart#albumart-in-directories-through-mpd).
Mpdevil _music lib_ only works locally, and I'm looking for some way to retrieve covers over LAN. 

And thanks so much for the best linux MPD client. Mpdevil it's really awesome!

**Comment by SoongNoonien** [comment]
> Can mpdevil retrieve the covers by this way?

Currently not but I'm working on it. Also keep in mind that version 2.0.0 (for `albumart`) or even 3.0.0 (for `readpicture`) of `python-mpd2` will be required on the remote machine when using mpdevil in a non flatpak environment.

 > Mpdevil music lib only works locally, and I'm looking for some way to retrieve covers over LAN.

Currently there a two different approaches I'm aware of to work around this. You could either mount your music lib via samba or NFS on the remote machine or sync a copy of your lib to the remote machine which only contains the covers (this should be relatively easy with rsync). But they are both not as good as using `albumart` or `readpicture`.

> And thanks so much for the best linux MPD client. Mpdevil it's really awesome!

I'm pleased to here! :)

**Comment by SoongNoonien** [comment]
With the newest commit mpdevil falls back to `albumart` and then to `readpicture` when no covers are found the normal way. I'm not sure if this will be the final implementation but I think it is ready for testing.

**Comment by SoongNoonien** [comment]
Please let me know if it is working as expected.

**Comment by lulis** [comment]
@SoongNoonien , sorry but I cannot succeed on getting `mpdevil` working building it from source.
Still getting this:
```
$ mpdevil 
(mpdevil:498045): GLib-GIO-ERROR **: 18:05:43.907: Settings schema 'org.mpdevil.mpdevil' is not installed
```
Any suggestions?

I'm on Ubuntu 20.04 x86_64 here.

**Comment by SoongNoonien** [comment]
Hi, did you run `sudo glib-compile-schemas /usr/share/glib-2.0/schemas`? (Maybe it is needed to change the path to `/usr/local/share` depending on where you installed it.)

**Comment by lulis** [comment]
Thanks, man, it did it.
Also, as you said earlier, I've removed the default `python3-mpd` (v1.1.0-1) and installed a newer version using pip.
So, for future reference, if someone (maybe me) needs to build it on Ubuntu 20.04:
```bash
$ sudo apt install python3-distutils-extra python3-gi python3-requests python3-bs4 
$ sudo pip3 install python-mpd2
$ sudo python3 setup.py install
$ sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas
$ sudo gtk-update-icon-cache
$ sudo update-desktop-database
```

Work like a charm!!!  
![Captura de tela de 2021-04-18 20-25-13](https://user-images.githubusercontent.com/6931166/115165418-3a597300-a084-11eb-9e25-7cecb2cab965.png)

**Comment by SoongNoonien** [comment]
Ok, I think we can close this bug then.
