### ISSUE TITLE
Feature Request: Add option to disable mpris

### ISSUE THREAD

**Issue by apfelkuchen6** [SoongNoonien/mpdevil#23]
### Rationale:
I'd prefer to have the mpris controls always available, even when mpdevil isn't open, but when using a headless mpd-mpris-control daemon like [mpDris2](https://github.com/eonpatapon/mpDris2), I end up with duplicate controls.

**Comment by SoongNoonien** [comment]
Hi!
I'm not sure if I understood you right, do you want an option to disable mpris or do you want mpdevil to expose the mpris interface even when the main window is closed?

**Comment by apfelkuchen6** [comment]
I was thinking about the former, but I guess both options would work for my use case. An mpd client itself being a daemon feels kind of weird and it's probably slightly more complicated to implement, so I'd just go with a setting to disable the mpris functionality of mpdevil.

Thanks!

**Comment by SoongNoonien** [comment]
> An mpd client itself being a daemon feels kind of weird and it's probably slightly more complicated to implement

I thought so too, that's why I asked.

**Comment by SoongNoonien** [comment]
This should be fixed now (in master). Please let me know if your problem is solved.

**Comment by apfelkuchen6** [comment]
This is perfect! Thanks a lot!
