### ISSUE TITLE
Settings schema 'org.mpdevil.mpdevil' does not contain a key named 'mpris'

### ISSUE THREAD

**Issue by paper42** [SoongNoonien/mpdevil#24]
This bug is a regression in 1.2.0.
```
%: mpdevil

(mpdevil:31746): GLib-GIO-ERROR **: 21:51:31.442: Settings schema 'org.mpdevil.mpdevil' does not contain a key named 'mpris'
Trace/breakpoint trap (core dumped)
```

**Comment by SoongNoonien** [comment]
Hi, how did you install mpdevil? Did you run `sudo glib-compile-schemas /usr/share/glib-2.0/schemas` (possible with a your local path)?

**Comment by paper42** [comment]
Oh, it seems like I had two glib schemas installed in two locations one from an older version. Thank you for pointing me in the right direction.
