### ISSUE TITLE
mpdevil hangs after installing python3-mpd 3.0.3

### ISSUE THREAD

**Issue by Forage** [SoongNoonien/mpdevil#26]
Today I took mpdevil for a spin (1.2.1) and it works nicely. Thank you for you effort.
With using Ubuntu 20.10, python3-mpd is stuck at version 1.1.0 which means no cover art being retrieved.
I downloaded python3-mpd 3.0.3 manually, but after installing it, mpdevil hangs as soon as it switches to an artist. Either switching to one automatically a start-up when MPD is already playing or manually when nothing is playing yet.
The only way to stop it is to force-quit the application.

Is there a way to get some debugging info to see what is happening?

**Comment by Forage** [comment]
It freezes completely, the whole application, no response what so ever. You have to kill it externally.
Nothing is added in the console in this state.

**Comment by SoongNoonien** [comment]
How long did you wait after it hangs? Is the cursor spinning? If you have very large covers or artists with many albums it may take some seconds to collect all covers. But I don't really think this is the problem, since 405 albums get loaded perfectly fine on my machine. Anyway it could be helpful to create a small test music collection with perhaps just one song to see if the error has something to do with your collection. Where did you load "python3-mpd" 3.0.3? With exactly the same version I can try to reproduce this on Ubuntu 20.10 under similar conditions. 
Two other questions about your MPD setup:
- How do you store your covers? (tags or extra image files)
- Are server and client on the same Machine?

**Comment by Forage** [comment]
I have 1346 albums in my collection, for which I waited about four minutes and 10 minutes, no cursor spinning.
The deb for version 3.0.3 came from https://packages.debian.org/bullseye/python3-mpd
Covers are all stored in the mp3 tags.
MPD 0.22.3 on a remote machine (RaspberryPi with music stored on a NAS accessed through an nfs share).

After some more testing it looks like the issue is limited to specific artists/albums.
I can systematically reproduce it for some, while others who have cover art as well don't cause the problem. In no case is cover art shown however.

What info, and how, can I provide for an artist that doesn't hang and one that does hang the application?

**Comment by SoongNoonien** [comment]
> What info, and how, can I provide for an artist that doesn't hang and one that does hang the application?

You can send me the songs via e-mail (in an archive with password) or via some sort of cloud. One song that causes the problem and one that causes no problem. Even a short stripe of the regarding songs is sufficient, when they still have the desired effect.

**Comment by Forage** [comment]
I've limited the issue even further. While checking for which artists make mpdevil hang I noticed it's only those of which I have m4a files. Artists with only mp3 files do not cause a problem.

I've sent you two files to your gmail address.

In case of the mp3 file I do not get to see cover art even though it's included in the file. In case of the m4a file it makes mpdevil hang, but only when v3.0.3 of python3-mpd is installed. If I revert back to 1.1.0 mpdevil does not hang and the files play just fine.

**Comment by SoongNoonien** [comment]
Ok, I did a first test with my normal setup (MPD 0.22.6, python-mpd2 3.0.4 and mpdevil 1.2.1) both client and server on the same machine. It works just fine. I'll install a Ubuntu 20.10 and see if I can reproduce it. Using my main machine as server hopefully will create a similar situation as with your raspi config.
![Bildschirmfoto_2021-05-19_20-09-03](https://user-images.githubusercontent.com/49582808/118863116-d0302a00-b8de-11eb-912b-7e1ab23e6209.png)
![Bildschirmfoto_2021-05-19_20-09-26](https://user-images.githubusercontent.com/49582808/118863147-d6bea180-b8de-11eb-98ce-d8346d581d05.png)

**Comment by SoongNoonien** [comment]
Btw, thanks for your effort on narrowing it down!

**Comment by SoongNoonien** [comment]
Using Ubuntu 20.10 and python3-mpd 3.0.3 still works fine for me. The only difference I can see now is the MPD version, and maybe the config. Is it possible for you to test a newer version? And can you send me your MPD config? I'll also try to get 0.22.3 working on another installation. Is 0.22.3 really the version of MPD or just the protocol in use reported by the "server stats" dialog of mpdevil? 
![Screenshot from 2021-05-19 22-11-38](https://user-images.githubusercontent.com/49582808/118878608-088c3400-b8f0-11eb-9537-7127e0588574.png)
![Screenshot from 2021-05-19 22-11-15](https://user-images.githubusercontent.com/49582808/118878655-1641b980-b8f0-11eb-91d0-5df93fd70ef0.png)

**Comment by Forage** [comment]
Strange. 

I'll see if I can get my hands on a more recent build tomorrow.

0.22.3 is the version reported by the mpd cli command itself. The reported protocol is 0.22.0.

**Comment by Forage** [comment]
Updating mpd to 0.22.6 fixed the issue.
Maybe it was the `fix "readpicture" on 32 bit machines` in version 0.22.4.
mpdevil is no longer hanging with m4a files and it is displaying its cover art.
Cover art of mp3 files is still not showing however, but I suppose that'll be mpd related as well.
