### ISSUE TITLE
Previous Media key behavior

### ISSUE THREAD

**Issue by dgcampea** [SoongNoonien/mpdevil#29]
Feature request: Allow _Previous_ media key to rewind to start of track (configurable in Settings for users who prefer old behavior).

Rewind behavior: when clicked once at any point, it should rewind to the start of track, and only if it gets clicked again in a short period of time, it should go to previous track (this allows any track to be manually repeated more than once).  For reference, Clementine Music Player has this behavior.

**Comment by dgcampea** [comment]
Clementine has it as:
![image](https://user-images.githubusercontent.com/59268455/121595814-957d6580-ca36-11eb-9805-a886005e641a.png)
![image](https://user-images.githubusercontent.com/59268455/121595945-bd6cc900-ca36-11eb-83fe-4222b01a6297.png)

If the above is too long, how short should it be?

**Comment by SoongNoonien** [comment]
Yes, I saw this while testing. :) It should be as short as the other options. If this is not possible I could add an explaining tooltip but this is not my preferred solution.

**Comment by dgcampea** [comment]
How about:
 
Previous Key behavior (dropdown box)
- Jump to previous song
- Restart song, jump to previous if pressed again

**Comment by dgcampea** [comment]
"Previous Key restarts tracks before jumping to the previous one"  ?
"Previous Key track-rewind mode" ?
It should be clear that quickly pressing it twice either doesn't do anything OR it jumps to previous track. (Other interpretations seem unlikely)

**Comment by SoongNoonien** [comment]
The newest commit implements the requested feature. The logic is as follows:
If the current song is running for more than _double-click-time_ it gets played again from the start.
If the current song is running for less than or exact _double-click-time_ the previous song gets played.
Where _double-click-time_ is the system double-click time configured in the settings of the desktop environment.

Note that the MPRIS interface was not changed, since the protocol specifies the current behavior. Please let me know if it works as expected. I used "previous button" instead of "previous key" to be consistent with "stop button".

**Comment by dgcampea** [comment]
The GUI button works but the keyboard multimedia button doesn't.

Querying `gtk-double-click-time` (unchanged value):
```
>>> import gi
>>> gi.require_version("Gtk", "3.0")    
>>> from gi.repository import Gtk
>>> Gtk.Settings.get_default().get_property("gtk-double-click-time")
400
```

As a side note/reference: Clementine does it by checking if 2 seconds have passed since last press (https://github.com/clementine-player/Clementine/blob/72c1f91c008cc0b23b9fc1a72cb8fc8dd451cee5/src/core/player.cpp#L372).

**Comment by dgcampea** [comment]
Although not within spec, changing MPRIS behavior for the Previous media key is what makes the option useful (since rewinding by clicking on UI can be already done by just double-clicking).

(reference: https://github.com/clementine-player/Clementine/blob/72c1f91c008cc0b23b9fc1a72cb8fc8dd451cee5/src/core/mpris2.cpp#L383)

**Comment by SoongNoonien** [comment]
> Querying gtk-double-click-time (unchanged value):...

Sorry, but I don't know what this should tell me.

> As a side note/reference: Clementine does it by checking if 2 seconds have passed since last press

I think 2 seconds is way to long. The default double-click should be a good choice. I tried to implement the function like a CD player does it and they mostly use a shorter interval that 2 seconds.

Anyway, I patched the MPRIS interface accordingly. Now it should work with the multimedia keys.

**Comment by dgcampea** [comment]
> > Querying gtk-double-click-time (unchanged value):...
> 
> Sorry, but I don't know what this should tell me.
> 

Oops, my bad, I've accidentally left it as debug info since it looked like it wasn't working (I was initially only testing with the media keys).
Ignore it :)

> > As a side note/reference: Clementine does it by checking if 2 seconds have passed since last press
> 
> I think 2 seconds is way to long. The default double-click should be a good choice. I tried to implement the function like a CD player does it and they mostly use a shorter interval that 2 seconds.

Using the current double-click timing choice is quite a bit faster than what I've usually seen with clementine or portable digital music players but it's not an absolute deal breaker. 
I left the reference here in case someone in the future raises an issue about this feature (due to differing setups or configs).

> 
> Anyway, I patched the MPRIS interface accordingly. Now it should work with the multimedia keys.

I can confirm d66526336608f9a3a92de55a1241af4d365c8d1e is working over here.

**Comment by SoongNoonien** [comment]
> I can confirm d665263 is working over here.

Ok, nice. :) So I'll close it than.

**Comment by dgcampea** [comment]
Thanks!
