### ISSUE TITLE
Add compatibility with media keys

### ISSUE THREAD

**Issue by alfreetos** [SoongNoonien/mpdevil#3]

**Comment by SoongNoonien** [comment]
I'll add it to the TODO-list.

**Comment by SoongNoonien** [comment]
I've enabled AudioPlay, AudioNext and AudioPrev in the latest commit. I haven't implemented any volume-key since it's rather a global thing done by the desktop environment, isn't it?

**Comment by alfreetos** [comment]
Yes it's globally mapped to the main volume.

**Comment by SoongNoonien** [comment]
All right. So did you test the recent master branch? Do the keys behave as expected?

**Comment by alfreetos** [comment]
No I'm getting no response from the application. I get a pop-up from the desktop showing me it does not recognise anything currently using the media keys:
![image](https://user-images.githubusercontent.com/5085846/73959983-0de38c00-4902-11ea-8c65-b4dcef7cc893.png)

**Comment by SoongNoonien** [comment]
I'm sorry I can't see anything on your screenshot. 

>  I get a pop-up from the desktop showing me it does not recognise anything currently using the media keys

When exactly do you get this pop-up? If your DE is using the media keys globally mpdevil has no chance to use them.

**Comment by SoongNoonien** [comment]
After a quick research I found this https://askubuntu.com/questions/990284/media-keys-not-working-on-ubuntu-17-10. Since Budgie is kind of related to gnome3 I'd say this is the issue. I'll try to implement a gnome compatibility. This should fix your problem too.

**Comment by alfreetos** [comment]
Yeah that must be the problem I'm having. The volume and mute button are already globally pre-mapped.

**Comment by SoongNoonien** [comment]
I've implemented a MPRIS interface (https://github.com/SoongNoonien/mpdevil/commit/73c7e911be5ae9705a9cc0558d70d30aad5fd228). Does it fix your issue?

**Comment by SoongNoonien** [comment]
I'll close this now. All my test were successful and I'm sure it's completely fixed.
