### ISSUE TITLE
Remove technical track details

### ISSUE THREAD

**Issue by Forage** [SoongNoonien/mpdevil#30]
The UI shows technical details like `256.0 kb/s, 44.1 kHz, 24 bit, 2 channels, mp3` for the track currently being played.
I think these details aren't that important to have available at all times. Especially for VBR tracks it makes the UI a bit 'nervous' with the number changing continuously. Removing the line all together cleans up the UI in general.
Personally I'm not a fan of adding yet another option for showing/hiding it either, but that could be a compromise.

**Comment by dgcampea** [comment]
Personally I like the display so I'd vote to keep it available with an option to toggle it than outright removal.

**Comment by SoongNoonien** [comment]
> Personally I like the display so I'd vote to keep it available with an option to toggle it than outright removal.

Me too. :) Therefore I added it. The status bar under the playlist was only added to display these information it the first place. But I see that this is not the perfect place for this track not playlist specific data. I use it very often (especially with VBRs) so I definitely wont remove it completely nor hide it automatically and I already got used to the current position in the GUI. A toggle in the settings would be an option. @Forage Should that option hide the entire status bar or just the "technical details" bit? I do not have any better ideas yet so any suggestions are welcome.

**Comment by Forage** [comment]
While the option to jump to the current song is not something I'd miss either, not having a way to clear the playlist might not be very practical.

Most of the technical data is already in the right-click popup of each song. Is having an additional direct view really that important? Can it be considered something you always want to know for each song?
It looks to me that "format" only needs some reformatting, changing the duration to MM:SS instead of seconds while you are at it ;-) It's only missing the bitrate, but that can be added, preferably the average (if available) in addition to the realtime when the song is playing.

**Comment by SoongNoonien** [comment]
> While the option to jump to the current song is not something I'd miss either, not having a way to clear the playlist might not be very practical.

Ok, so hiding only the "technical details" bit seems to be the better choice.

> Most of the technical data is already in the right-click popup of each song. Is having an additional direct view really that important? Can it be considered something you always want to know for each song?

Yes! :) Before I wrote mpdevil I used cantata and when they added these technical details (as option) I liked them right away from the start. So this feature had to be in my own client as well.

> It looks to me that "format" only needs some reformatting, changing the duration to MM:SS instead of seconds while you are at it ;-)

Yes, good point. "time" and "duration" are both the length of the song. "time" is already converted to MM:SS and "duration" is the more exact value so I thought it would be ok to leave it unconverted. But I could omit "time" and converted "duration" instead, the unconverted value is always visible as tooltip. This would remove some redundancy and "time" is deprecated anyways and shouldn't be used anymore.

> It's only missing the bitrate, but that can be added, preferably the average (if available) in addition to the realtime when the song is playing.

Sadly this is not possible since as far as I know MPD does not provide this functionality. The right-click popup already shows all metadata MPD is providing.

**Comment by SoongNoonien** [comment]
The right-click popup is now reformatted accordingly.

**Comment by SoongNoonien** [comment]
Hi!
I made a small test to see how it looked without the technical details. I think it looks odd. What do you think? The blank space is a bit wasted, isn't it?

![Bildschirmfoto_2021-06-08_20-48-35](https://user-images.githubusercontent.com/49582808/121241358-a645a400-c89b-11eb-8e02-4e06807b1152.png)

![Bildschirmfoto_2021-06-08_20-49-35](https://user-images.githubusercontent.com/49582808/121241400-af367580-c89b-11eb-8a6f-6f06ba42b8c0.png)

**Comment by Forage** [comment]
It's nice and clean space at the same time ;-)

I never actually tried it but if the playlist allows selecting multiple tracks to e.g. delete those I wouldn't even miss the bar at all.

**Comment by SoongNoonien** [comment]
> I never actually tried it but if the playlist allows selecting multiple tracks to e.g. delete those I wouldn't even miss the bar at all.

You can always use shift+del. After this test I think hiding the whole bar definitely looks nicer.

**Comment by SoongNoonien** [comment]
Oh, I forgot the screenshot.
![Bildschirmfoto_2021-06-08_22-41-58](https://user-images.githubusercontent.com/49582808/121254671-d47eb000-c8aa-11eb-8483-34a58ccbce3f.png)

**Comment by Forage** [comment]
Love it :) Nice and clean and no more distraction from constant jumping numbers. Many thanks

**Comment by nousernouser** [comment]
Hi
I have a very wide collection of classic music (FLAC + CueFile) of CD and SuperCD quality, which I listen to via an audio server connected with a good level hi-fi system (and, only for images, with an LCD TV).
I'm trying mpdevil as the main MPD client for my audio station, with the mpdevil's interface displayed on my TV.
For me it is *essential* to have *all* the technical data of the listening songs displayed, including -- even and above all -- the instant bitrate.
So, please, keep in view all the technical details !!!
Or a configuration option to decide whether to show them or not.
Thank you 
Regards

**Comment by Forage** [comment]
I remain amazed by the absolute urgency to have this information at hand that some have. Almost as if that changes anything about the music you are listening to, while it's the listening part that is the main goal of using MPD in the first place. You're going through a lot of trouble of finding a different placement for something that should not be considered the highest priority and which is already one single right-click away.

It might help determining why it is so important to see it right away to know if it's worth the trouble and what would be a suitable way of showing it.

**Comment by SoongNoonien** [comment]
> ...one single right-click away
As I said earlier, there is no way of showing the bit rate of an arbitrary song. MPD only exposes the bit rate for the current song.

**Comment by Forage** [comment]
> > ...one single right-click away
> 
> As I said earlier, there is no way of showing the bit rate of an arbitrary song. MPD only exposes the bit rate for the current song.

But you _can_ show it in the same pop-up when the song is actually playing ;-) For the other songs you display something like "n/a (not playing)" or "n/a (during playback only)" if you have the space.

**Comment by SoongNoonien** [comment]
Hi!
Yesterday I pushed some commits to master. The "technical track details" are now optional, they can be toggled via the "Show audio format" check button in the settings (enabled by default). The action/statusbar of the playlist window was removed. The current playlist length and duration are now shown in the header of the "title" column. And the back button which scrolls to the currently playing song in the playlist is now only visible (in the bottom left corner of the playlist) when it is needed. Only the clear button is completely gone but the short key is still there and wont be removed. If I find another place for it in the future I might readd it, but I don't consider this button an important component of the players control flow. Please let me know if it is working as expected.
![Bildschirmfoto vom 2021-07-17 11-39-18](https://user-images.githubusercontent.com/49582808/126033126-7d4a0395-b76a-402a-b3be-fc746b77dee5.png)

**Comment by Forage** [comment]
Nicely done, thanks!
The only remark I have is the playlist duration. It seems to me that putting that value in the length column header would be more appropriate than the title column header.

**Comment by SoongNoonien** [comment]
> It seems to me that putting that value in the length column header would be more appropriate than the title column header.

Yes, you are right but there is hardly enough space. ;-) I think it is still not randomly placed and can be easily found by new users.
So I consider this solved then.
