### ISSUE TITLE
mpdevil fails if there are multiple artists tags (even multiple album artist tags)

### ISSUE THREAD

**Issue by bloomvdomino** [SoongNoonien/mpdevil#4]
If a file have multiple artist tags (separated by NULL per id3v2.4 specification), they aren't correctly recognized by mpdevil. They are displayed right in the left artist sidebar, but adding them to the playlist results in error like this:

```
Traceback (most recent call last):
  File "/usr/bin/mpdevil", line 1696, in on_playlist_changed
    self.store.set(treeiter, 0, track, 1, disc, 2, title, 3, artist, 4, album, 5, duration, 6, year, 7, genre, 8, song["file"], 9, Pango.Weight.BOOK)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1051, in set
    _set_lists(args[::2], args[1::2])
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1045, in _set_lists
    values.append(self._convert_value(col_num, value))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 914, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 210, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 249, in set_value
    raise TypeError("Expected string but got %s%s" %
TypeError: Expected string but got ['Melissa Benoist', 'Grant Gustin']<class 'list'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mpdevil", line 1698, in on_playlist_changed
    self.store.append([track, disc, title, artist, album, duration, year, genre, song["file"], Pango.Weight.BOOK])
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 997, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 988, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 900, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 914, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 210, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 249, in set_value
    raise TypeError("Expected string but got %s%s" %
TypeError: Expected string but got ['Melissa Benoist', 'Grant Gustin']<class 'list'>
```

They are correctly recognized and sorted by MPD and mpdevil sends the correct playlist to MPD and all songs are played. Only the playlist box stucks in a state, where for e.g. songs from the previous album are listed.

You can see the issue on the screenshot below:

![Screenshot](https://user-images.githubusercontent.com/33204710/78602584-fd468800-7856-11ea-9006-c5afdc80aa30.png)

That's the right tracklisting:

![Screenshot](https://user-images.githubusercontent.com/33204710/78602793-56aeb700-7857-11ea-80c0-d5a9bc1503b6.png)

**Comment by SoongNoonien** [comment]
Ok, I'll fix this. But I have to admit, I've no idea how to create such a file for testing. Which program did you use to add multiple artist tags?

**Comment by bloomvdomino** [comment]
On Windows you can use MP3Tag, multiple tags with NULL are delimited with an double backslash, for example the artist tag for one of the files from above would be "Melissa Benoist\\Grant Gustin". You can recheck the right parsing if you right click on the file in the left panel and select Extended tags. When there are multiple tags from the same type underneath the first one, it worked!

On Linux you can use Kid3(-qt). Multiple tags are delimited with the pipe symbol ("|").

**Comment by bloomvdomino** [comment]
Yes, I think that would be the format expected by the most people; separated by comma with a space after each comma. Some programs separate them by semicolon without space, but that's worse readable than comma with space, in my opinion.

**Comment by SoongNoonien** [comment]
Ok, I'll go for the commas with spaces.

**Comment by SoongNoonien** [comment]
I've committed a fix. I tested it with some .mp3 and .ogg files. To try it just install mpdevil directly from master or if you are using Arch you can use my git PKGBUILD.

```
# Maintainer: Martin Wagner <grisu-04@web.de>
# Contributor: Martin Wagner <grisu-04@web.de>

pkgname=mpdevil
pkgver=v0.4.4.r2.g08ff73d
pkgrel=1
pkgdesc="A small MPD client written in python"
arch=('any')
license=('GPL3')
url="https://github.com/SoongNoonien/mpdevil"
depends=('python-mpd2' 'gtk3' 'libnotify' 'python-gobject' 'python-requests' 'python-beautifulsoup4' 'python-dbus')
makedepends=('intltool')
source=('git+https://github.com/SoongNoonien/mpdevil.git')
md5sums=('SKIP')

pkgver() {
  cd "$pkgname"
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
  cd "${srcdir}/${pkgname}"
  NOCONFIGURE=1 ./autogen.sh
}

build() {
  cd "${srcdir}/${pkgname}"
  ./configure --prefix=/usr 
  make
}

package() {
  cd "${srcdir}/${pkgname}"
  make DESTDIR="${pkgdir}" install
}

```

**Comment by bloomvdomino** [comment]
I tested it with a lot of albums, as I use multiple tags a lot. All of them worked! I'll close the issue...

**Comment by SoongNoonien** [comment]
Thanks a lot for testing!
