### ISSUE TITLE
Disc number column emptied after play

### ISSUE THREAD

**Issue by Forage** [SoongNoonien/mpdevil#41]
Hi,

I found a minor issue in 1.3.0.

When starting to play an album the `Disc` column is filled for all the tracks. However, after a track has finished playing the disc column value of that track is emptied and remains empty.

![Screenshot from 2021-08-26 14-49-50](https://user-images.githubusercontent.com/550915/130966049-78081981-f0b1-4c04-8255-7bb26e56225d.png)

It does not happen when you jump to the next from one that is playing.

Tested with just MP3 files and running mpdevil on Ubuntu 21.04 with MPD 0.22.9.
Let me know if you need a test file or if you're already able to reproduce it with your own.

**Comment by dgcampea** [comment]
@Forage do forward this issue to MPD upstream as this affects multiple clients
