### ISSUE TITLE
directory browsing

### ISSUE THREAD

**Issue by storrgie** [SoongNoonien/mpdevil#42]
Would it be possible/acceptable to add a feature for directory/filesystem based browsing?

**Comment by SoongNoonien** [comment]
Hi, I'm very sorry but this feature is not planed. I neither will implement it myself nor accept feature requests addressing this.

**Comment by dgcampea** [comment]
> Would it be possible/acceptable to add a feature for directory/filesystem based browsing?

Cantata can do this if you're looking for an alternative mpd client.
