### ISSUE TITLE
Possibly port to MacOS?

### ISSUE THREAD

**Issue by ghost** [SoongNoonien/mpdevil#44]
I really like this program, far better than any other gui client for mac (or linux ftm). I have this running on my Thinkpad which has Arch installed, but I really would like to run this on my new Macbook. How could this possibly be done? Im more than willing to help

**Comment by SoongNoonien** [comment]
Hi!
This should technically be possible but I have nearly no experience with MacOS. While GTK and Python shouldn't be a problem, I don't see an alternative to MPRIS/dbus (Do you know one?) and libnotify (Apparently libnotify actually is available, can you confirm?). But I think the main problem is to package it up, perhaps this https://gitlab.gnome.org/GNOME/gtk-mac-bundler can simplify it. I have a MacOS running (in a virtual machine) so I should be able to try if I can run it their after installing all requirements and maybe a little patching (removing MPRIS and the notifications). I once run it on windows so MacOS should also be possible, but this has a low priority for me.

**Comment by dgcampea** [comment]
Maybe https://pypi.org/project/osxmmkeys/ can solve the MPRIS issue here?

**Comment by SoongNoonien** [comment]
This package seems to implement just a tiny fraction of MPRISes functionalities. But it might be worth a closer look.

**Comment by SoongNoonien** [comment]
Closing, as the original poster has left the platform and I'm probably not able to implement this.
