### ISSUE TITLE
Group by album

### ISSUE THREAD

**Issue by Svadkos** [SoongNoonien/mpdevil#46]
It would be really great to have some way to choose full album even if it's a compilation of songs by different artists.

**Comment by SoongNoonien** [comment]
This is already possible by using the "AlbumArtist" tag to group albums with various artists e.g. compilations.

**Comment by auroraanna** [comment]
Picture an album of which each song is made by a different artist but all artists share the same label (under which the album is released). It does not make sense to me to label make the name of the label the AlbumArtist because the label is not an artist, several artists made the album and there is a dedicated Label attribute.

**Comment by SoongNoonien** [comment]
@auroraanna Plattenalbum does not read the `label` tag. Please have a look at https://github.com/SoongNoonien/plattenalbum/issues/128#issuecomment-2220551388.

**Comment by auroraanna** [comment]
This is not answering the problem. AlbumArtist is is not the correct tag.

**Comment by auroraanna** [comment]
though uhm… after reading some specs, they don't agree on the attributes/frames/comments exist. In ID3, `Publisher` should be used as the field for the label while in vorbis comments, `Organisation` should be used, which doesn't even agree with ID3. Neither of them seem to have an `AlbumArtist` however.

**Comment by auroraanna** [comment]
> This is not answering the problem. AlbumArtist is is not the correct tag.

point being though that i don't want a music player program to make me label my music less semantically correct.

**Comment by SoongNoonien** [comment]
Citing from the [docs](https://mpd.readthedocs.io/en/latest/protocol.html#tags) of mpd:

> albumartist: on multi-artist albums, this is the artist name which shall be used for the whole album. The exact meaning of this tag is not well-defined.

So, as it is not "well-defined" (btw "well-defined" is not even "well-defined") it certainly can be used in this case here. At least I'm using it for this use case and therefore Plattenalbum interprets it this way.

**Comment by SoongNoonien** [comment]
> though uhm… after reading some specs, they don't agree on the attributes/frames/comments exist. In ID3, Publisher should be used as the field for the label while in vorbis comments, Organisation should be used, which doesn't even agree with ID3. Neither of them seem to have an AlbumArtist however.

So, in my opinion AlbumArtist is a good compromise. Tagging music files is hard and one as to make compromises anyway...

**Comment by SoongNoonien** [comment]
> point being though that i don't want a music player program to make me label my music less semantically correct.

Is it really less correct if you simply add the AlbumArtist tags? As far as I understand, you currently don't use the AlbumArtist tag at all, do you?
