### ISSUE TITLE
Make lyrics button optional (toggle in settings)

### ISSUE THREAD

**Issue by bloomvdomino** [SoongNoonien/mpdevil#5]
My music library is much focussed on album arts, and I usually don't care about lyrics, but the lyrics button permanently covers the right corner of the album art.

Wouldn't it be a good idea to add an toggle in the settings to optionally disable the lyrics button?

**Comment by SoongNoonien** [comment]
Thanks for your feedback! I expected to get some critics on this. I decided to permanently show the lyrics button since the auto hide made me crazy after some time of using it.

> Wouldn't it be a good idea to add an toggle in the settings to optionally disable the lyrics button?

Sure it's no big deal. Should the setting completely disabled it, place it elsewhere or just auto hide it like in 0.8.2? Or is there a better solution? I'm open for suggestions.

**Comment by bloomvdomino** [comment]
The position per se is good I think; that's the first place I instinctively would search for that button.

I think two options would be considerable:

1. Hiding the button completely if the setting is toggled.
2. Move it to the right of the progress bar (left of the volume slider and right of the queue controls) and style it in the same way as the volume slider. (That would be the second place I would search for a that button).

Personally I would prefer the first solution as in my opinion it is more intuitive.

**Comment by SoongNoonien** [comment]
Ok, I'll go for option one. If the lyrics button is hidden there is no way to show the lyrics window anymore. Should I add a keybinding (e.g ctrl+L) to open it anyway?

**Comment by bloomvdomino** [comment]
I think that would be a good compromise for those who don't want to have the button but still want to use the lyrics window. :+1:

**Comment by SoongNoonien** [comment]
I just added an option to disable the lyrics button and a keybinding (ctrl + l) to open it anyway. Please let me know if it is working correctly.

**Comment by bloomvdomino** [comment]
Tested all possible cases. Works correctly and without any glitches! :+1:
