### ISSUE TITLE
cover art - missing in dedicated panel, visible in browser

### ISSUE THREAD

**Issue by 97-109-107** [SoongNoonien/mpdevil#52]
I'm a long time cantata user, and I enjoy your fresh take and especially the mini player mode, thanks!

I have noticed that album cover art does not display in the dedicated window above the playlist. This happens for all albums, even those who have their cover art displayed in the browser part. I have setup the path to the library in the settings panel and all of my library has embedded cover art.

Is this expected behaviour, or do you need more details to diagnose this?

**Comment by SoongNoonien** [comment]
> Is this expected behaviour, or do you need more details to diagnose this?

No this is not expected behaviour. Yes I need more details. Which version of mpdevil and mpd do you use? Is something printed on the console when running the program there?

**Comment by 97-109-107** [comment]
No console output without `-d`

Versions
- Mpd 0.23.7
- Mpdevil 1.70

I'm pasting output from running with `-d` for a few seconds while mpd is currently playing - [https://0x0.st/oBv7.out](https://0x0.st/oBv7.out)

**Comment by 97-109-107** [comment]
Seeing that you asked me for a cover file - I just realized that one point might need to be underlined in my original message 

- My music collection has no cover art files 
- My collection has embedded coveart (which is displayed in the browser of MPDdevil and all other mpd clients)

If we're on the same page here, I can proceed and share a file

**Comment by SoongNoonien** [comment]
Embedded covers are support by mpdevil and do work perfectly fine with my files. So I think I need a music file from your collection to see if it triggers the bug here.

**Comment by SoongNoonien** [comment]
Thanks for the file but it is working just fine over here:
![Bildschirmfoto_2022-05-31_22-29-17](https://user-images.githubusercontent.com/49582808/171279201-ae4b9ae6-a93a-4f98-bc6a-056420af2a9f.png)

**Comment by 97-109-107** [comment]
It's not, please see those two below - mpdevil and cantata respectively. 

Could this be an issue with the gui toolkit?

![ScreenShot 'Mpdevil' 0x6a00007 20220531 224051](https://user-images.githubusercontent.com/1902438/171280841-594e347e-ace9-48fc-8e45-f5c9a4f9a14f.png)

![ScreenShot 'cantata' 0x5800006 20220531 224200](https://user-images.githubusercontent.com/1902438/171281049-d7028a90-f4be-4b36-889f-acd35b2dc814.png)

**Comment by 97-109-107** [comment]
Indeed it seems to be a theme or GTK issue, however, this is beyond my understanding. Below is a screenshot of XFCE running another GTK theme.
![2022-06-06_18-06](https://user-images.githubusercontent.com/1902438/172200578-b6b71fbe-b5c1-40d5-8b84-09216e67962f.png)

I will inform the author of the dekstop enviroment which I used in previous screenshot - [NsCDE](https://github.com/NsCDE/NsCDE) (which is based on FVWM). As far as I understand, it generates it's own GTK themes. 

Thanks for your prompt responses, I will inqure further about the ``Gtk.EventBox`` theming.

**Comment by topas-rec** [comment]
I see the same behavior, but I'm on arch and I use the gnome desktop.
I have no idea how to proceed with this issue? Where to report? gnome?

**Comment by topas-rec** [comment]
Thanks for your help.

> What theme are you using?

Cannot check right now but I'll report back.
Since I did not knowingly modified the theme I think I use the arch default theme. From [the arch wiki](https://wiki.archlinux.org/title/GTK#Themes):

> In GTK 3 and GTK 4, the default theme is Adwaita, but HighContrast and HighContrastInverse themes are also included. In GTK 2, the default theme is Raleigh, but Arch Linux has a custom configuration file at `/usr/share/gtk-2.0/gtkrc`, which sets the default theme to Adwaita. 

> Did you verify that it really is the theme?

No. Can I verify by switching the theme?
(I assume I can follow the arch wiki for doing that)

**Comment by SoongNoonien** [comment]
> No. Can I verify by switching the theme?
> (I assume I can follow the arch wiki for doing that)

Yes, that should be sufficient.

**Comment by SoongNoonien** [comment]
The most recent commit fixes this issue even when using a theme like the original poster did. If you are still experiencing this bug after updating (on arch you can simply use the mpdevil-git package) then it has another cause.

**Comment by topas-rec** [comment]
> The most recent commit fixes this issue even when using a theme like the original poster did. If you are still experiencing this bug after updating (on arch you can simply use the mpdevil-git package) then it has another cause.

Works. Thanks for your help.
Hint: Changing the theme from Adwaita to deepin didn't solve the issue. I was just playing with the themes when I read your comment.

**Comment by SoongNoonien** [comment]
> Hint: Changing the theme from Adwaita to deepin didn't solve the issue. I was just playing with the themes when I read your comment.

Adwaita is working perfectly fine over here, I'm testing the player almost solely with Adwaita. So you were probably experiencing something different that was not caused by the theme.

**Comment by topas-rec** [comment]
I was perhaps a but imprecise.
The issue is gone with the latest commit.

I changed the theme BEFORE I knew you committed something. I was trying to find out if it was really the theme that causes the issue as you mentioned before.

Again: after the latest commit Adwaita theme works fine. 👍🏾
Thanks and sorry for the confusion.

**Comment by SoongNoonien** [comment]
>  Thanks and sorry for the confusion.

There was no confusion. I understood you the first time. 😉️

I was just wondering what caused the issue on your machine as it wasn't exactly the same that caused it on the original posters machine. I'm pretty sure the Adwaita theme would have worked for the original poster. In his case the problem could be solved on the theming side. That's all I was referring to in my last comment.

**Comment by topas-rec** [comment]
Ah, now I understand.
