### ISSUE TITLE
Display albumartistsort instead of albumartist on the left pane

### ISSUE THREAD

**Issue by animaldaydream** [SoongNoonien/mpdevil#54]
The left pane sorts the album artists by albumartist_sort, but it displays every credit they've been given as well.

This is very confusing as the albums contained in every entry don't make sense to me.

If we could optionally merge using the albumartistsort and mb_albumid tags it'd work perfectly. Aditionally we could customize the appearance of our library without messing up the scrobbling to Last.fm.

The albumartistsort tags are also linked to the MBIDs the same way as the albumartist tags are.

[Not that I scrobble to Last.fm anymore. It's a mess.]

**Comment by animaldaydream** [comment]
Additionally, it would be nice to show the actual albumartist tag under the artwork as credit.

Well, this is the way MusicBrainz Picard automatically tags files anyways.

**Comment by animaldaydream** [comment]
It's also worth knowing that using multiple values on the albumartist and artist fields will successfully create and populate each entry.

If we could keep this behaviour that'd be great.

**Comment by SoongNoonien** [comment]
I don't know what you mean, could you please clarify?

**Comment by animaldaydream** [comment]
OK, I'll try to be clear, but it'll take a while.

MusicBrainz Picard tags artists using six different fields.

`artist`: The **track artist as credited, concatenated with connectors** used in the official credits.
`albumartist`: The **album artist as credited, concatenated with connectors** used in the official credits.
`artists`: (mind the 's') a **multi-value tag with each track artist**, as credited.
`albumartists`: (mind the 's') a **multi-value tag with each album artist**, as credited.
`artistsort`: The **sort name of each track artist** as stored in the MusicBrainz database, except concatenated with connectors used in the official credits. 
`albumartistsort`: The sort name of each album artist as stored in the MusicBrainz database, except concatenated with connectors used in the official credits.

Now, MPD only takes the tags `artist` `artistsort` `albumartist` `albumartistsort`, so the other two tags can't be used.

The problem:

Currently, tagging with Picard, you'd have two different spellings of the artist capsule/CAPSULE, and three different spellings of the artist LOONA/이달의 소녀/今月の少女, which are actually the same artist. In the case of CAPSULE, the name is a change of alias made at a point in time. In the case of LOONA, it's the official translations of the group's name used internationally, in Korea, and in Japan, but are actually considered the same artist.

The solutions:

Manually, you could take all the offending files and replace the `artist` and `albumartist` tags with standard names, but it is kind of a chore. For people who tag automatically using Picard or beets, and rely on the MusicBrainz database for clean tags, it's a bit of a mess.

I actually made a few scripts for Picard so that the tags picked by MPD would be multi-valued instead of concatenated, and each artist would have a standardised name.

But if mpdevil populated the left pane with `albumartistsort` tags instead, this would be taken care of automatically, as the sort name is supposed to be standard.

**This is a huge mess to figure out,** but it's doable. [Following this reply I'll add the scripts I use with Picard to fix this issue automatically.]

**Comment by SoongNoonien** [comment]
I'm sorry this is not a problem of mpdevil. As you already discovered it can be solved by editing the tags. That the tag changes affect the scrobbling abilities is not at all a problem for me as I'm not supporting this. I don't think the albumartistsort tag is a tag that should be visible in the browser, it is just a hint for sorting.

> Do you use MusicBrainz UUIDs to disambiguate artists with the same name?

No, I'm not using any MusicBrainz tags.
