### ISSUE TITLE
Gentoo ebuild link

### ISSUE THREAD

**Issue by allaboutmikey** [SoongNoonien/mpdevil#57]
The Gentoo instructions say download the ebuild, but it's not clear where from. The link given is useful (how to make a custom repo in Gentoo), but there should also be a link to https://github.com/SoongNoonien/mpdevil/releases/latest to show where the ebuild file actually can be downloaded.

**Comment by SoongNoonien** [comment]
Actually there already is such a link. I added the link to the beginning of the section "Package Installation", so I don't have to add it to all distribution specific installation instructions.
