### ISSUE TITLE
flatpak based on old gnome version

### ISSUE THREAD

**Issue by pitlochry** [SoongNoonien/mpdevil#58]
The flatpak is stilled based on gnome Platform 41. Now we have 42, and in two weeks 43. 
mpdevil is the last flatpak out of many which relys on/needs this old branch. 
When do you plan to move ahead? Thanks for letting us enjoy your application.

**Comment by SoongNoonien** [comment]
I published a new release and updated the flatpak manifest accordingly. Please open bug reports specifically targeting the flatpak package here: https://github.com/flathub/org.mpdevil.mpdevil/issues.

**Comment by pitlochry** [comment]
Wow. Thank you for your fast response.
