### ISSUE TITLE
Stuck while compiling

### ISSUE THREAD

**Issue by praise-you** [SoongNoonien/mpdevil#6]
First thing first: thanks a lot for your hard work, Markus!
I'm very bad at compiling. I use Manjaro and the AUR depository to avoid compiling stuff I want!
I tried to compile 0.8.3 and I don't know where it hangs. Autogen begins with:

> Please add the files codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4  progtest.m4

I had to find them online and copied them into the aclocal folder.
I also checked if config.guess and config.sub are present and I found files with these names.
Here's my ./autogen.sh terminal output:

> $ sudo ./autogen.sh 
> *** WARNING: I am going to run 'configure' with no arguments.
> *** If you wish to pass any to it, please specify them on the
> *** './autogen.sh' command line.
> 
> Copying file po/Makefile.in.in
> 
> Please add the files
>   codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
>   progtest.m4
> from the /usr/share/aclocal directory to your autoconf macro directory
> or directly to your aclocal.m4 file.
> You will also need config.guess and config.sub, which you can get from
> ftp://ftp.gnu.org/pub/gnu/config/.
> 
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force 
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: configure.ac: not using Autoheader
> autoreconf: running: automake --add-missing --copy --force-missing
> autoreconf: Leaving directory `.'
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... none
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking locale.h usability... yes
> checking locale.h presence... yes
> checking for locale.h... yes
> checking for LC_MESSAGES... yes
> checking for CFPreferencesCopyAppValue... no
> checking for CFLocaleCopyCurrent... no
> checking libintl.h usability... yes
> checking libintl.h presence... yes
> checking for libintl.h... yes
> checking for ngettext in libc... yes
> checking for dgettext in libc... yes
> checking for bind_textdomain_codeset... yes
> checking for msgfmt... /usr/bin/msgfmt
> checking for dcgettext... yes
> checking if msgfmt accepts -c... yes
> checking for gmsgfmt... /usr/bin/msgfmt
> checking for xgettext... /usr/bin/xgettext
> checking for catalogs to be installed...  de
> checking whether NLS is requested... yes
> checking for intltool-update... /usr/bin/intltool-update
> checking for intltool-merge... /usr/bin/intltool-merge
> checking for intltool-extract... /usr/bin/intltool-extract
> checking for xgettext... (cached) /usr/bin/xgettext
> checking for msgmerge... /usr/bin/msgmerge
> checking for msgfmt... (cached) /usr/bin/msgfmt
> checking for gmsgfmt... (cached) /usr/bin/msgfmt
> checking for perl... /usr/bin/perl
> checking for perl >= 5.8.1... 5.30.2
> checking for XML::Parser... ok
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.16... yes
> checking for a Python interpreter with version >= 3.0... python
> checking for python... /usr/bin/python
> checking for python version... 3.8
> checking for python platform... linux
> checking for python script directory... ${prefix}/lib/python3.8/site-packages
> checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
> checking for gtk 3.0 installed... found
> checking for MPDClient installed... found
> checking for beautifulsoup installed... found
> checking for requests installed... found
> checking for dbus installed... found
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating po/Makefile.in
> config.status: creating bin/Makefile
> config.status: creating data/Makefile
> config.status: creating data/mpdevil.desktop.in
> config.status: executing depfiles commands
> config.status: executing default-1 commands
> config.status: executing po/stamp-it commands

Then with:

> $ sudo make
> Making all in bin
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/bin'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/bin'
> Making all in data
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po mpdevil.desktop.in mpdevil.desktop
> Found cached translation database
> Merging translations into mpdevil.desktop.
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> Making all in po
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/po'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/po'
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3'
> make[1]: Nothing to be done for 'all-am'.
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3'

And the last one:

> $ sudo make install
> Making install in bin
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/bin'
> make[2]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/bin'
>  /usr/bin/mkdir -p '/usr/local/bin'
>  /usr/bin/install -c mpdevil '/usr/local/bin'
> make[2]: Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/bin'
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/bin'
> Making install in data
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> make[2]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> make[2]: Nothing to be done for 'install-exec-am'.
>  /usr/bin/mkdir -p '/usr/local/share/applications'
>  /usr/bin/install -c -m 644 mpdevil.desktop '/usr/local/share/applications'
>  /usr/bin/mkdir -p '/usr/local/share/icons/hicolor/48x48/apps'
>  /usr/bin/install -c -m 644 mpdevil.png '/usr/local/share/icons/hicolor/48x48/apps'
>  /usr/bin/mkdir -p '/usr/local/share/icons/hicolor/scalable/apps'
>  /usr/bin/install -c -m 644 mpdevil.svg '/usr/local/share/icons/hicolor/scalable/apps'
> if test -n "org.mpdevil.gschema.xml"; then \
> 	test -z "/usr/local/share/glib-2.0/schemas" || /usr/bin/mkdir -p "/usr/local/share/glib-2.0/schemas"; \
> 	/usr/bin/install -c -m 644 org.mpdevil.gschema.xml "/usr/local/share/glib-2.0/schemas"; \
> 	test -n "" || /usr/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas; \
> fi
> make  install-data-hook
> make[3]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> *** Icon cache not updated.  After (un)install, run this:
> ***   gtk-update-icon-cache -f -t /usr/local/share/icons/hicolor
> make[3]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> make[2]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/data'
> Making install in po
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/po'
> linguas="de "; \
> for lang in $linguas; do \
>   dir=/usr/local/share/locale/$lang/LC_MESSAGES; \
>   /bin/sh /home/me/.local/share/Trash/files/mpdevil-0.8.3/install-sh -d $dir; \
>   if test -r $lang.gmo; then \
>     /usr/bin/install -c -m 644 $lang.gmo $dir/mpdevil.mo; \
>     echo "installing $lang.gmo as $dir/mpdevil.mo"; \
>   else \
>     /usr/bin/install -c -m 644 ./$lang.gmo $dir/mpdevil.mo; \
>     echo "installing ./$lang.gmo as" \
> 	 "$dir/mpdevil.mo"; \
>   fi; \
>   if test -r $lang.gmo.m; then \
>     /usr/bin/install -c -m 644 $lang.gmo.m $dir/mpdevil.mo.m; \
>     echo "installing $lang.gmo.m as $dir/mpdevil.mo.m"; \
>   else \
>     if test -r ./$lang.gmo.m ; then \
>       /usr/bin/install -c -m 644 ./$lang.gmo.m \
> 	$dir/mpdevil.mo.m; \
>       echo "installing ./$lang.gmo.m as" \
> 	   "$dir/mpdevil.mo.m"; \
>     else \
>       true; \
>     fi; \
>   fi; \
> done
> installing de.gmo as /usr/local/share/locale/de/LC_MESSAGES/mpdevil.mo
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3/po'
> make[1]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3'
> make[2]: Entering directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3'
> make[2]: Nothing to be done for 'install-exec-am'.
> make[2]: Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3'
> make[1]: Leaving directory '/home/me/.local/share/Trash/files/mpdevil-0.8.3'

Thanks a lot for any help!

**Comment by SoongNoonien** [comment]
> First thing first: thanks a lot for your hard work, Markus!

Thanks! But who is Markus? :)

> I had to find them online and copied them into the aclocal folder.
> I also checked if config.guess and config.sub are present and I found files with these names.

These files are not important it works fine without them. Though I have to admit it is my first time providing a compilable package. But so far it's working good on all distros I have tested.

According to your terminal output mpdevil should start just fine now. Did you try the PKGBUILD which I provide for all releases of mpdevil? It's working great with Manjaro too. With a PKGBUILD you don't have to compile it by hand, just run e.g. `makepkg -sirc` in the directory of the PKGBUILD.

**Comment by praise-you** [comment]
> Thanks! But who is Markus? :)

Martin! Sorry :grin: 

> According to your terminal output mpdevil should start just fine now.

No for me :wink: 

> Did you try the PKGBUILD which I provide for all releases of mpdevil? It's working great with Manjaro too. With a PKGBUILD you don't have to compile it by hand, just run e.g. `makepkg -sirc` in the directory of the PKGBUILD.

Thanks a lot for this command! I had no idea what to do with that file. I was able to install mpdevil! I've learned something new today. But now it doesn't work at all. No GUI and after 10 seconds the Force Quit window shows up. I then tried to run it from the terminal and it doesn't give any message.

> $ makepkg -sirc
> ==> Making package: mpdevil 0.8.3-1 (dim. 05 juil. 2020 15:46:16)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Downloading v0.8.3.tar.gz...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   128  100   128    0     0   1828      0 --:--:-- --:--:-- --:--:--  1802
> 100 1064k    0 1064k    0     0  1183k      0 --:--:-- --:--:-- --:--:-- 1183k
> ==> Validating source files with sha256sums...
>     v0.8.3.tar.gz ... Passed
> ==> Extracting sources...
>   -> Extracting v0.8.3.tar.gz with bsdtar
> ==> Starting prepare()...
> aclocal: installing 'm4/glib-gettext.m4' from '/usr/share/aclocal/glib-gettext.m4'
> aclocal: installing 'm4/gsettings.m4' from '/usr/share/aclocal/gsettings.m4'
> aclocal: installing 'm4/intltool.m4' from '/usr/share/aclocal/intltool.m4'
> aclocal: installing 'm4/nls.m4' from '/usr/share/aclocal/nls.m4'
> aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
> Copying file po/Makefile.in.in
> 
> Please add the files
>   codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
>   progtest.m4
> from the /usr/share/aclocal directory to your autoconf macro directory
> or directly to your aclocal.m4 file.
> You will also need config.guess and config.sub, which you can get from
> ftp://ftp.gnu.org/pub/gnu/config/.
> 
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force 
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: configure.ac: not using Autoheader
> autoreconf: running: automake --add-missing --copy --force-missing
> configure.ac:22: installing './compile'
> configure.ac:6: installing './install-sh'
> configure.ac:6: installing './missing'
> Makefile.am: installing './INSTALL'
> autoreconf: Leaving directory `.'
> Skipping configure process.
> ==> Starting build()...
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... none
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking locale.h usability... yes
> checking locale.h presence... yes
> checking for locale.h... yes
> checking for LC_MESSAGES... yes
> checking for CFPreferencesCopyAppValue... no
> checking for CFLocaleCopyCurrent... no
> checking libintl.h usability... yes
> checking libintl.h presence... yes
> checking for libintl.h... yes
> checking for ngettext in libc... yes
> checking for dgettext in libc... yes
> checking for bind_textdomain_codeset... yes
> checking for msgfmt... /usr/bin/msgfmt
> checking for dcgettext... yes
> checking if msgfmt accepts -c... yes
> checking for gmsgfmt... /usr/bin/msgfmt
> checking for xgettext... /usr/bin/xgettext
> checking for catalogs to be installed...  de
> checking whether NLS is requested... yes
> checking for intltool-update... /usr/bin/intltool-update
> checking for intltool-merge... /usr/bin/intltool-merge
> checking for intltool-extract... /usr/bin/intltool-extract
> checking for xgettext... (cached) /usr/bin/xgettext
> checking for msgmerge... /usr/bin/msgmerge
> checking for msgfmt... (cached) /usr/bin/msgfmt
> checking for gmsgfmt... (cached) /usr/bin/msgfmt
> checking for perl... /usr/bin/perl
> checking for perl >= 5.8.1... 5.30.2
> checking for XML::Parser... ok
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.16... yes
> checking for a Python interpreter with version >= 3.0... python
> checking for python... /usr/bin/python
> checking for python version... 3.8
> checking for python platform... linux
> checking for python script directory... ${prefix}/lib/python3.8/site-packages
> checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
> checking for gtk 3.0 installed... found
> checking for MPDClient installed... found
> checking for beautifulsoup installed... found
> checking for requests installed... found
> checking for dbus installed... found
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating po/Makefile.in
> config.status: creating bin/Makefile
> config.status: creating data/Makefile
> config.status: creating data/mpdevil.desktop.in
> config.status: executing depfiles commands
> config.status: executing default-1 commands
> config.status: executing po/stamp-it commands
> Making all in bin
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/bin'
> sed -e s!\@datadir\@!/usr/share!  -e s!\@libdir\@!/usr/lib!  -e s!\@version\@!0.8.3! < mpdevil.py > mpdevil
> chmod +x mpdevil
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/bin'
> Making all in data
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po mpdevil.desktop.in mpdevil.desktop
> /usr/bin/glib-compile-schemas --strict --dry-run  --schema-file=org.mpdevil.gschema.xml && mkdir -p . && touch org.mpdevil.gschema.valid
> Generating and caching the translation database
> Merging translations into mpdevil.desktop.
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> Making all in po
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/po'
> file=`echo de | sed 's,.*/,,'`.gmo \
>   && rm -f $file && /usr/bin/msgfmt -o $file de.po
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/po'
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3'
> make[1]: Nothing to be done for 'all-am'.
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3'
> ==> Entering fakeroot environment...
> ==> Starting package()...
> Making install in bin
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/bin'
> make[2]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/bin'
> make[2]: Nothing to be done for 'install-data-am'.
>  /usr/bin/mkdir -p '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/bin'
>  /usr/bin/install -c mpdevil '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/bin'
> make[2]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/bin'
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/bin'
> Making install in data
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> make[2]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> make[2]: Nothing to be done for 'install-exec-am'.
> if test -n "org.mpdevil.gschema.xml"; then \
> 	test -z "/usr/share/glib-2.0/schemas" || /usr/bin/mkdir -p "/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/glib-2.0/schemas"; \
> 	/usr/bin/install -c -m 644 org.mpdevil.gschema.xml "/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/glib-2.0/schemas"; \
> 	test -n "/home/me/wip/@build_folder/mpdevil/pkg/mpdevil" || /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas; \
> fi
>  /usr/bin/mkdir -p '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/applications'
>  /usr/bin/mkdir -p '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/icons/hicolor/48x48/apps'
>  /usr/bin/mkdir -p '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/icons/hicolor/scalable/apps'
>  /usr/bin/install -c -m 644 mpdevil.desktop '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/applications'
>  /usr/bin/install -c -m 644 mpdevil.svg '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/icons/hicolor/scalable/apps'
>  /usr/bin/install -c -m 644 mpdevil.png '/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/icons/hicolor/48x48/apps'
> make  install-data-hook
> make[3]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> *** Icon cache not updated.  After (un)install, run this:
> ***   gtk-update-icon-cache -f -t /usr/share/icons/hicolor
> make[3]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> make[2]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/data'
> Making install in po
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/po'
> linguas="de "; \
> for lang in $linguas; do \
>   dir=/home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/locale/$lang/LC_MESSAGES; \
>   /bin/sh /home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/install-sh -d $dir; \
>   if test -r $lang.gmo; then \
>     /usr/bin/install -c -m 644 $lang.gmo $dir/mpdevil.mo; \
>     echo "installing $lang.gmo as $dir/mpdevil.mo"; \
>   else \
>     /usr/bin/install -c -m 644 ./$lang.gmo $dir/mpdevil.mo; \
>     echo "installing ./$lang.gmo as" \
> 	 "$dir/mpdevil.mo"; \
>   fi; \
>   if test -r $lang.gmo.m; then \
>     /usr/bin/install -c -m 644 $lang.gmo.m $dir/mpdevil.mo.m; \
>     echo "installing $lang.gmo.m as $dir/mpdevil.mo.m"; \
>   else \
>     if test -r ./$lang.gmo.m ; then \
>       /usr/bin/install -c -m 644 ./$lang.gmo.m \
> 	$dir/mpdevil.mo.m; \
>       echo "installing ./$lang.gmo.m as" \
> 	   "$dir/mpdevil.mo.m"; \
>     else \
>       true; \
>     fi; \
>   fi; \
> done
> installing de.gmo as /home/me/wip/@build_folder/mpdevil/pkg/mpdevil/usr/share/locale/de/LC_MESSAGES/mpdevil.mo
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3/po'
> make[1]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3'
> make[2]: Entering directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3'
> make[2]: Nothing to be done for 'install-exec-am'.
> make[2]: Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3'
> make[1]: Leaving directory '/home/me/wip/@build_folder/mpdevil/src/mpdevil-0.8.3'
> ==> Tidying install...
>   -> Removing libtool files...
>   -> Purging unwanted files...
>   -> Removing static library files...
>   -> Stripping unneeded symbols from binaries and libraries...
>   -> Compressing man and info pages...
> ==> Checking for packaging issues...
> ==> Creating package "mpdevil"...
>   -> Generating .PKGINFO file...
>   -> Generating .BUILDINFO file...
>   -> Generating .MTREE file...
>   -> Compressing package...
> ==> Leaving fakeroot environment.
> ==> Finished making: mpdevil 0.8.3-1 (dim. 05 juil. 2020 15:46:27)
> ==> Installing package mpdevil with pacman -U...
> [sudo] password for me: 
> Sorry, try again.
> [sudo] password for me: 
> loading packages...
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (1) mpdevil-0.8.3-1
> 
> Total Installed Size:  0,14 MiB
> 
> :: Proceed with installation? [Y/n] y
> (1/1) checking keys in keyring                                           [########################################] 100%
> (1/1) checking package integrity                                         [########################################] 100%
> (1/1) loading package files                                              [########################################] 100%
> (1/1) checking for file conflicts                                        [########################################] 100%
> (1/1) checking available disk space                                      [########################################] 100%
> :: Processing package changes...
> (1/1) installing mpdevil                                                 [########################################] 100%
> :: Running post-transaction hooks...
> (1/4) Arming ConditionNeedsUpdate...
> (2/4) Compiling GSettings XML schema files...
> (3/4) Updating icon theme caches...
> (4/4) Updating the desktop file MIME type cache...
> ==> Cleaning up...

**Comment by SoongNoonien** [comment]
Did you remove your old install attempt? If not: by running mpdevil on the console (and starting in the applications menu) the old files will be used. Please try to run `/usr/bin/mpdevil` directly.

**Comment by praise-you** [comment]
Actually i was a naughty boy. At one time I searched for all mpdevil files in the system partition and deleted them. That's how I got rid of it.

Since then, I've run PKGBUILD in a clean folder and installed it correctly. I've even rebooted.

> $ /usr/bin/mpdevil 
> **_(after a minute)_** connect failed **_(GUI appears and is freezed)_**
> ^C^C^C^C^C^Cconnect failed
> Traceback (most recent call last):
>   File "/usr/bin/mpdevil", line 3462, in <module>
>     app.run(sys.argv)
>   File "/usr/lib/python3.8/site-packages/gi/overrides/Gio.py", line 44, in run
>     return Gio.Application.run(self, *args, **kwargs)
>   File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
>     next(self.gen)
>   File "/usr/lib/python3.8/site-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
>     signal.default_int_handler(signal.SIGINT, None)
> KeyboardInterrupt

I didn't tell you that a month ago I had managed to build an older version. Yesterday I was setting up a new MPD instance and gave mpdevil the new connection details. Since then it started to hang, which led me to upgrade it. Maybe mpdevil is stuck because of an conf file and I wasn't able to find where it could be located.

Sorry for the mess and thank you for your support!

**Comment by SoongNoonien** [comment]
> I didn't tell you that a month ago I had managed to build an older version. Yesterday I was setting up a new MPD instance and gave mpdevil the new connection details. Since then it started to hang, which led me to upgrade it. Maybe mpdevil is stuck because of an conf file and I wasn't able to find where it could be located.

Ok, I see.

A suggestion:

Just run `gsettings reset-recursively org.mpdevil` in a terminal to clear all settings of mpdevil. If it still won't start just use `gsettings set org.mpdevil hosts "['foo']"` to set an illegal host.

**Comment by praise-you** [comment]
> Just run `gsettings reset-recursively org.mpdevil` in a terminal to clear all settings of mpdevil.

Yes! Everything is fine. :grinning: 

Thank you so much! It doesn't show the album covers but I suppose I'll have to tweaks MPD's conf. Should I create a new enhancement request to display the lyrics tag of songs?

Now I have to fix my server and get the soundcard working...

**Comment by SoongNoonien** [comment]
> Yes! Everything is fine. grinning

Great!

> It doesn't show the album covers but I suppose I'll have to tweaks MPD's conf.

You have to set a music library location for your profile in mpdevil to load the covers from (I think should explain than the wiki). Currently mpdevil can't load covers from the tags since neither mpd nor python-mpd2 support than at the moment but it is planed for mpd I think.

> Should I create a new enhancement request to display the lyrics tag of songs?

I'm sorry but same problem here. mpdevil can only load lyrics from the web since mpd does not support lyrics tags. Since I want to keep mpdevil small I actually didn't intent to load tags directly. So you could try to make a feature request for mpd.

**Comment by SoongNoonien** [comment]
Besides that the GUI should never freeze. Could you send me your mpd.conf which made mpdevil hang so I can see if mpdevil needs fixing in that point?

**Comment by praise-you** [comment]
Hey sorry for letting you wait! I was very busy and actually it got too difficult to set up mpd for me, so I deleted it. I don't have my conf anymore...

**Comment by SoongNoonien** [comment]
Oh, ok. I think I'll close this bug then.
