### ISSUE TITLE
Request: re-add right click popover in Artist list

### ISSUE THREAD

**Issue by bryal** [SoongNoonien/mpdevil#60]
I'm using this feature regularly -- right clicking on an artist (or "all artists" in a genre) and queueing / playing all their tracks. Sometimes I just don't have a particular album in mind, and just want to randomly play tracks of certain artist. This feature was very useful for that.

I believe 1bd340927c254f00eb63af56ec1eae8aff113af0 is the commit that removed this. I don't know if there was any particular reason it had to be removed, but if possible, I would personally very much appreciate if it was re-added!

**Comment by SoongNoonien** [comment]
The player was build around albums so I decided that albums should be the biggest unit to add to the playlist. To choose entire artists as biggest unit seems kind of arbitrary as there are also genres. As you pointed out it was even possible to add entire genres but there was no right click menu in the genre list. I think the browser has a much clearer structure now, the genre list and artist list are solely used to filter and the album list is used to play/add.
You can still add entire artists or genres to the playlist via the search. I understand that this is not as easy as it was but this particular use case is not in what I consider the scope of this project.

**Comment by bryal** [comment]
Ok, thank you anyways! I quite like this music player otherwise, so I will remain on 1.8.1 or create a personal fork then.
