### ISSUE TITLE
Feature Request: Random Album Page

### ISSUE THREAD

**Issue by Richjn** [SoongNoonien/mpdevil#61]
Hi
I've been using mpdevil for quite some time now and love it, thank you for making this project available.
I have over 120k tracks and more than 1.5k artists in my collection and sometimes it's a bit overwhelming selecting an album. A feature I would love to see would be an addition to the list of artist "Random Albums" where, say, 10 random albums are displayed click the heading again and get another 10 etc. Would help to rediscover albums and start the music discovery for that session.
I have no desire to see bloat added to mpdevil but feel this feature may be appreciated by anyone with a large collection.

Thanks
Richard

**Comment by SoongNoonien** [comment]
Hi.
> I've been using mpdevil for quite some time now and love it, thank you for making this project available.

Thanks for your appreciation.

I've already experimented with such a feature in the past and now again because of your request. And I'm not happy with it. An additional entry in the artists list like "Random Albums" is not very fitting I think. It just doesn't belong there. The only possibility I came up with is to introduce a way to select one random album in the browser. In my tests I used a shortcut for this which is clearly not ideal, for an actual implementation a button of some kind would be necessary.
So, I'm currently not planing to add such a feature as it is not important enough for me.

**Comment by Richjn** [comment]
Hi
Thanks for considering this feature and I respect your decision not to
implement it but one last thought from me if I can.

Currently mpdevil opens with the first artist in your list selected and
their albums displayed. In my case I get to see 10cc every time I open
mpdevil.
Perhaps one way to handle introducing a random album feature would be
to display an opening page of random album with no further options
which would not pollute the interface, the user would simply select one
of the random albums or select an artist from the list as normal.

Just a thought

-----Original Message-----
From: Martin Wagner ***@***.***>
Reply-To: SoongNoonien/mpdevil
***@***.***>
To: SoongNoonien/mpdevil ***@***.***>
Cc: Richjn ***@***.***>, Author ***@***.***>
Subject: Re: [SoongNoonien/mpdevil] Feature Request: Random Album Page
(Issue #61)
Date: 12/11/22 22:28:46

Hi.
> I've been using mpdevil for quite some time now and love it, thank
> you for making this project available.
Thanks for your appreciation.
I've already experimented with such a feature in the past and now again
because of your request. And I'm not happy with it. An additional entry
in the artists list like "Random Albums" is not very fitting I think.
It just doesn't belong there. The only possibility I came up with is to
introduce a way to select one random album in the browser. In my tests
I used a shortcut for this which is clearly not ideal, for an actual
implementation a button of some kind would be necessary.
So, I'm currently not planing to add such a feature as it is not
important enough for me.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by SoongNoonien** [comment]
> If I continue to use this, I'll clean it up and put it somewhere... let's see.

I'd be interested to have a look at it.
