### ISSUE TITLE
Translation Updates

### ISSUE THREAD

**Issue by SoongNoonien** [SoongNoonien/mpdevil#67]
Hi @MasFlam, @ersen0 and @grosmanal!

Since version 1.10.0 there are some new menus which are currently only translated into German. If you are still using mpdevil please update your language so I can make a new release with more up to date translations. The current mpdevil.pot contains all new strings though it might be necessary to update the specific .po file before all new strings are visible there too.

Thanks again for your work!

**Comment by MasFlam** [comment]
Sure, I'll do it sometime this weekend :)
