### ISSUE TITLE
Change default album artwork

### ISSUE THREAD

**Issue by lorenzgillner** [SoongNoonien/mpdevil#7]
Hi! First of all, this program deserves more attention, it's great!

But I have one little request and don't want to create a whole pull request for it:

Could you please change the value of the default icon for albums with no available artwork from the application icon to "media-optical" (rendering of  a CD)?
Position: `bin/mpdevil.py:689:76`

This looks more pleasing and it also makes more sense to show a plain CD for tracks without artwork than the little red devil, in my opinion.

LG

**Comment by SoongNoonien** [comment]
> Hi! First of all, this program deserves more attention, it's great!

Thanks!

> Could you please change the value of the default icon for albums with no available artwork from the application icon to "media-optical" (rendering of a CD)?

I've changed it. "media-optical" actually looks quite nice. Please let me know if it works as expected.

Martin

**Comment by lorenzgillner** [comment]
Thank you, works perfectly!

Keep up the good work!

LG
