### ISSUE TITLE
Possible option to swap playback_control/playback_options?

### ISSUE THREAD

**Issue by s0ulslack** [SoongNoonien/mpdevil#71]
Love the app, used daily! I'm one of those that can't leave enough alone and modify stuff that triggers my OCD. I swap playback_control/playback_options to put the controls near the volume button. Not for everyone but maybe enough that a Settings option would be viable to add?

Thanks so much for the great client

**Comment by SoongNoonien** [comment]
Hi, thanks for your appreciation!
But I won't add an option for this as I really don't think that enough users would need it.
