### ISSUE TITLE
Support multiple genres

### ISSUE THREAD

**Issue by nangiloc** [SoongNoonien/mpdevil#74]
It's common for people to tag their music with multiple genres. For example I can have an album A with the tag "pop, female vocalists", an album B with "folk, female vocalists" and an album C with "pop".

mpdevil displays the three tags as they are. Would it be possible to add an option to parse the tags and separate them according to a specific character (here the comma)? This would display the genres "pop", "female vocalists" and "pop" independently of each other.

In this example, selecting the genre "pop" should show albums A and C, "female vocalists" A and B, and "folk" only B.

If it were also possible to select several genres at the same time, selecting "pop" and "female vocalists" should only display album A.

Thank you for this great project.

**Comment by SoongNoonien** [comment]
Hi!
It is possible to add multiple values for the genre tag. This means that your file will have multiple tags which are all called "genre" but with different values. You need a tag editor that supports this though. I'm using kid3, which is able to do exactly that, simply add a new tag field which is also called genre but with a different value. Here is an example:


![Bildschirmfoto_2023-06-17_10-33-12](https://github.com/SoongNoonien/mpdevil/assets/49582808/40a55ba5-f909-4429-8c08-c395d07ac4c8)

> In this example, selecting the genre "pop" should show albums A and C, "female vocalists" A and B, and "folk" only B.

This would be the case.

**Comment by nangiloc** [comment]
Thanks for the fast answer.

Looks like beets should support multiple tags anytime soon. Maybe. There is a pull request.

And about multiple genres selection? Any chance?

**Comment by SoongNoonien** [comment]
> And about multiple genres selection? Any chance?

No, currently not.
