### ISSUE TITLE
Sort artists alphabetically ignoring leading "The"

### ISSUE THREAD

**Issue by Newbytee** [SoongNoonien/mpdevil#79]
At least in my "circle of music enthusiasts", alphabetical artist sorting is done without considering the "The" part of the name. So, for example "The Beatles" would be considered starting with a "B" rather than "T". Would this be reasonable to implement at least as an option in mpdevil?

**Comment by SoongNoonien** [comment]
It is already implemented. You need to specify an `albumartistsort` tag. In this particular case something like "Beatles" for all files with an `albumartist` tag "The Beatles".

**Comment by Newbytee** [comment]
Thanks, I guess I should learn more about metadata.
