### ISSUE TITLE
Album cover fallback

### ISSUE THREAD

**Issue by chinmaya1011** [SoongNoonien/mpdevil#8]
Sometimes, instead of using "cover.jpg" and the like for album covers, "\<album artist\> - \<album name\>" is used. Users should be allowed to configure mpdevil to fall back to any images it finds in the same directory as the track, or, better, enter their own regular expression string to find album covers.

**Comment by SoongNoonien** [comment]
What do you mean by 
> " - " is used

?

> ...or, better, enter their own regular expression string to find album covers.

I could integrate this feature into the profile settings. But this will take some time since they generally need a small review.

**Comment by chinmaya1011** [comment]
Sorry, I forgot that the GitHub markdown parser treats \<\>s specially. Fixed my original comment.

**Comment by SoongNoonien** [comment]
I did find some time to make a first test. The newest commit implements a regex config in the profile settings. Please let me know if it works as expected.

**Comment by chinmaya1011** [comment]
It works! Thanks so much :)
When can we expect this in a release?

**Comment by SoongNoonien** [comment]
>  When can we expect this in a release?

I think in the next few days.
