### ISSUE TITLE
Currently playing tracks view is too narrow and has to be expanded on every startup

### ISSUE THREAD

**Issue by Newbytee** [SoongNoonien/mpdevil#80]
When I start up mpdevil, the sidebar on the right that shows the album cover and list of queued tracks is too narrow by default (see screenshot). It would be nice if it was wider so that I could read the titles and see the album cover without having to expand it manually every time I start mpdevil. I feel like this one is a regression, but I don't know when it started happening exactly, so I might be misremembering.

![image](https://github.com/SoongNoonien/mpdevil/assets/4428753/98f1ee64-6389-44ae-850a-7bb2532ba351)

**Comment by Newbytee** [comment]
> Are you running mpdevil in maximized state?

Yes

**Comment by SoongNoonien** [comment]
Can you try in normal mode and see if it persists? So I mean unmaximize it, set an appropriate size for the playlist and so on and then close and reopen.

**Comment by Newbytee** [comment]
> Can you try in normal mode and see if it persists? So I mean unmaximize it, set an appropriate size for the playlist and so on and then close and reopen.

It behaves as expected if the window isn't maximised, i.e., it opens like this:

![image](https://github.com/SoongNoonien/mpdevil/assets/4428753/2874e303-4419-4174-9ed4-e0155e56c598)

**Comment by SoongNoonien** [comment]
Ok, I had noticed similar problems a long time ago with the maximized state. But I invested quite some time into it and at least on my machines it is fixed now. The general problem is that it is quite hard to know for a fact that the window is actually maximized from within the program, this lead to critical races where sometimes the column widths inside the window were restored before the window was maximized. So could you give some more details about your system so I can try to reproduce it over here? i.e. what desktop and window manager are you using and their versions

**Comment by Newbytee** [comment]
It's Fedora 38 with GNOME 44. mpdevil is installed via the Flatpak from Flathub.

**Comment by SoongNoonien** [comment]
Ok, I was able to reproduce it but only on about every 10th startup. So it seems the race condition is still present. I'll see what I can do to fix it.

**Comment by SoongNoonien** [comment]
So I've looked into it and found at least one possible solution. But this as the side effect that the window size of the unmaximized state gets lost. This means if you close mpdevil in maximized state, reopen it an then unmaximize it, it won't actually get smaller. The border will reappear as usual and it will be movable and resizeable again but the previous size is lost. Do you think that this is a problem? I've taken a look at other apps, some behave like this (e.g. virtualbox) and some like the file manager of xfce (thunar) have a problem similar to this bug.

**Comment by Newbytee** [comment]
> So I've looked into it and found at least one possible solution. But this as the side effect that the window size of the unmaximized state gets lost. This means if you close mpdevil in maximized state, reopen it an then unmaximize it, it won't actually get smaller. The border will reappear as usual and it will be movable and resizeable again but the previous size is lost. Do you think that this is a problem? I've taken a look at other apps, some behave like this (e.g. virtualbox) and some like the file manager of xfce (thunar) have a problem similar to this bug.

For my use-case this wouldn't be an issue, but it does sound like it could be annoying for others. I'm not sure I'm qualified to answer the question though.

**Comment by SoongNoonien** [comment]
Please let me know if current master fixes the issue for you.

**Comment by Newbytee** [comment]
> Please let me know if current master fixes the issue for you.

Latest master works for me, apart from the aforementioned issue where windowing it doesn't restore previous dimensions after a restart :)

**Comment by SoongNoonien** [comment]
Ok, so I'll close this now.

**Comment by niels0n** [comment]
I have this problem too, on Arch, installed from AUR.

> Can you try in normal mode and see if it persists? So I mean unmaximize it, set an appropriate size for the playlist and so on and then close and reopen.

This seems to work, but when I reopen it sometimes it's small again...

**Comment by SoongNoonien** [comment]
> I have this problem too, on Arch, installed from AUR.

Is it the `mpdevil-git` package and is it up to date?

**Comment by niels0n** [comment]
No, it's `mpdevil`. Should I install `mpdevil-git` instead of it?

**Comment by SoongNoonien** [comment]
Yes, a haven't had the time to make a new release yet.

**Comment by niels0n** [comment]
I just installed it, but unfortunately it happens there too.
![Screenshot_2023-09-08_13-33-00](https://github.com/SoongNoonien/mpdevil/assets/47432766/d171db28-1637-48e8-8e75-3a2d18fc8c45)
