### ISSUE TITLE
Play all songs

### ISSUE THREAD

**Issue by niels0n** [SoongNoonien/mpdevil#81]
Hey, I like that mpdevil is pretty album-centric, but I can't find a way to add all songs to the playlist and play them. The only way to do it seems to be to manually append them one by one and then play, but having 1000+ songs this is clearly not an option.
Is this possible somehow, or is mpdevil supposed to be used just to play single albums? Sorry if this may be obvious, but I'm struggling to find a way to do it.

**Comment by SoongNoonien** [comment]
Hi!

> Is this possible somehow, or is mpdevil supposed to be used just to play single albums?

No sorry, this is not possible.
