### ISSUE TITLE
Add support for mpdmomd and mpdfavd

### ISSUE THREAD

**Issue by Paradyx** [SoongNoonien/mpdevil#85]
This feature request is twofold: 

1. I would like to have the option to display the ratings and play-counts of tools like [mpdpopm](https://github.com/sp1ff/mpdpopm) and [mpdfav](https://github.com/vincent-petithory/mpdfav) in the client. 
2. I would like to rate my music from within the client. Although, this can be substituted by hotkeys in the window-manager. 

Both tools proposed here, save their state inside the mpd stickers and should be easy to use with mpdevil. Since most people probably appreciate the simplicity of mpdevil, this feature should be hidden behind a feature flag similar to MPRISv2, etc.

**Comment by SoongNoonien** [comment]
I'm sorry it took me so long, but this is completely out of scope for the project.
