### ISSUE TITLE
Artist list exhibits stuttery scrolling behavior when scrolling with trackpad

### ISSUE THREAD

**Issue by rien333** [SoongNoonien/mpdevil#88]
## Description

Whenever I scroll in the artist list with my laptop's build-in trackpad, the scroll area jumps around erratically (see videos below). Interestingly, when I use the scroll wheel on my regular bluetooth mouse, there's no stuttering. Other applications and `mpdevil` views do not exhibit comparable behavior. 

Because the issue only occurs when using my trackpad, it could be that the issue relates to smooth scrolling, which Gnome disables on regular mouse devices. Smooth scrolling gives scroll actions some lingering momentum,  which might be confusing the view. 

Needless to say, this issue makes scrolling the artist list extremely difficult on laptops/trackpads, more so than a video could demonstrate. 

This has been happening ever since I've started using mpdevil in December, so this bug might have been introduced in the adwaita rewrite? 

If you don't have access to a trackpad, I would be happy to test a patch. 

## Demonstration 

* Scrolling with my trackpad :

[Screencast from 2024-01-21 17-28-47.webm](https://github.com/SoongNoonien/mpdevil/assets/10417027/9e8389a0-a3fa-4ae3-83eb-736186123dcf)

In this video, I performed two vertical swipes in succession. The view keeps scrolling after having completed the swipe (what I called "momentum), which seemingly leads to it erratic jumping/stuttering, even after I've completely stopped making contact with the trackpad. This stuttering  is especially apparent  towards the end of the video.

* Scrolling with my regular mouse: 

[Screencast from 2024-01-21 17-29-17.webm](https://github.com/SoongNoonien/mpdevil/assets/10417027/8fb39abb-df2e-4f80-9251-070ba93b3841)

## Version info

**OS**: Arch Linux
**mpdevil**: most recent commit

**Comment by SoongNoonien** [comment]
Sadly these kinds of bugs are very hard to track down. I'm using a `Gtk.ListView` for all lists in the main window including the artist list. This widget was introduced in GTK4 and has been very broken in past especially scrolling has been a big problem (https://gitlab.gnome.org/GNOME/gtk/-/issues/2971). So I'm relatively sure that this is a bug of GTK4.

Are there any messages printed onto the console while the issue occurs?

> Other applications and mpdevil views do not exhibit comparable behavior.

From playing around with similar issues in the past I've learnt that these problems often only occur with relatively large lists. So did you try to make the queue roughly as long as your artist list to reproduce it in there? Also could you give me an estimate of the number of artists in your list so I can try to create a simpler test program with the same problem?

> If you don't have access to a trackpad, I would be happy to test a patch.

Unfortunately this is indeed the case.

**Comment by SoongNoonien** [comment]
Currently the only actual difference I see between the artist list and the other lists in mpdevil are the dictionary-like initial letters. This is a relatively new feature added only very recently in `GTK4-4.12`. I've added a new branch to the repo called `scrolling` which disables this. Could you test this and see if the issue still is present there, just to eliminate this as a potential cause?

**Comment by rien333** [comment]
> Are there any messages printed onto the console while the issue occurs?

Nothing but the expected calls to mpd (tested with `--debug` for good measure).

> So did you try to make the queue roughly as long as your artist list to reproduce it in there? Also could you give me an estimate of the number of artists in your list so I can try to create a simpler test program with the same problem?

Interestingly, the queue does not exhibit this behavior! I have 820 artists in my library currently, and I've tried to reproduce the issue with up to 2000 songs in my queue. 

More interestingly, and probably worth mentioning upstream, is that if I make a new library with just 37 artists, I cannot reproduce the issue. This matches your prior suspicions. 

 > Could you test this [branch] and see if the issue still is present there, just to eliminate this as a potential cause?
 
 I will try this in a bit! Though after reading the issue you linked, I do expect this bug to be firmly on Gtk's side. (mentioning https://gitlab.gnome.org/GNOME/gtk/-/issues/5793 here for me to return to later, as this is a recent issue related to kinetic scrolling.)

**Comment by rien333** [comment]
> Could you test this [branch] and see if the issue still is present there, just to eliminate this as a potential cause?

Interestingly,  the issue does not occur on the `scrolling` branch! This aligns with the fact that queue list does not exhibit buggy scrolling.

Still, the issue might be firmly on Gtk's side. If you think some of the observations about list length and the like are of any broader interest, 
I can try and report some of the findings here over at their repo.

**Comment by SoongNoonien** [comment]
> Interestingly, the issue does not occur on the scrolling branch! This aligns with the fact that the queue list does not exhibit buggy kinetic scrolling.

Ok, now I should be able to create a simple reproducer.

> Still, the issue might be firmly on Gtk's side. If you think some of the observations about list length and the like are of any broader interest,

Yes, I think so too.

> I can try and report some of the findings here over at their repo.

This could be helpful since they are convinced the issue is not present in `Gtk.ListView`.

**Comment by SoongNoonien** [comment]
The following test script should reproduce the issue [scrolling.py.txt](https://github.com/SoongNoonien/mpdevil/files/14029632/scrolling.py.txt). I had to upload it as `.txt` since github seems not to support `.py` files.

**Comment by SoongNoonien** [comment]
> Does the drag bar use the same problematic Gtk.ListView widget ?

I'm not sure if I understand you correctly but the drag bar is just controlling the `Gtk.ListView` widget. The drag bar itself is part of the `Gtk.ScrolledWindow` surrounding the `Gtk.Listview`.

**Comment by rien333** [comment]
@Richjn are you also on the latest commit of `mpdevil`, or are you on the last stable release?

**Comment by rien333** [comment]
@SoongNoonien 

Did you see this comment already?

> In Music we had multi-line labels for the title in the albums grid view (max 2 lines), so the height varied slightly per-grid-row. This indeed exhibited both problems mentioned.
For now we fixed the albums to just use 1 line per album title (gnome-music!1037 (merged)) and the scrolling issues seem to be gone, confirming the suspicions. 

(source: https://gitlab.gnome.org/GNOME/gtk/-/issues/6344#note_1983042)

**Comment by SoongNoonien** [comment]
> Did you see this comment already?

No, I did not. But this is probably the same problem we have with the initial letters. They seem to be a bit taller than the normal artist names.

**Comment by Richjn** [comment]
@rien333 I'm on git Master.
I always update before commenting on an issue in case it's already been fixed.

**Comment by SoongNoonien** [comment]
@rien333 I https://github.com/SoongNoonien/mpdevil/discussions/91#discussioncomment-8655415 you wrote:
> I'm just hoping the artists list view issue arising from the changes in GTK4 can be resolved because mpdevil is painful to the point of not being useable, for me, currently with my 3k+ artists list.

I could at least for now disable the initial letters in the artist list. Previous tests suggested that this fixes the scrolling problem. What do you think about that? Are these initial letters even useful with such large collections?

**Comment by rien333** [comment]
> Are these initial letters even useful with such large collections?

 I kind of like them, but they also pose some internalization/localization problems. In particular, they are helpful if most of your library is in some kind of latin script, but what if most of your library is, say, k-pop, or includes tons of  Japanese bands?  I've looked at the code a bit, and I can't really find an elegant solution to this problem.
 
 I think for those reasons, most projects 1) either opt to not use this type of UI altogether (IIRC, gnome music takes this approach), or 2) generate initial letters based on _all_ artist in your library, including the non-western ones (this is what the lollypop music player does).  I do not really like option #2, since  it creates extra runtime computation and doesn't generate super nice results if you have a relatively small set of non-western artists. 
 

 For instance, I can't imagine the following looking nice if you seperate them into categories based on the first letter of each artist: 
 

![image](https://github.com/SoongNoonien/mpdevil/assets/10417027/b85a1e45-02c2-4f5c-821a-35751677acd0)

**Comment by SoongNoonien** [comment]
> In particular, they are helpful if most of your library is in some kind of latin script, but what if most of your library is, say, k-pop, or includes tons of Japanese bands? I've looked at the code a bit, and I can't really find an elegant solution to this problem.

Yes, this is a problem I couldn't solve as well.

> I think for those reasons, most projects 1) either opt to not use this type of UI altogether (IIRC, gnome music takes this approach), or 2) generate initial letters based on all artist in your library, including the non-western ones (this is what the lollypop music player does).

In earlier versions I did it like lollypop but this had other drawbacks. For instance it is very hard to combine this with natural localized sort which ignores diacritics like Ä,Ö,Ü in German.

**Comment by Richjn** [comment]
What would work for me would be an artists search limited to the initial letter markers as this would at least jump me to the approximate position of the artist I was looking for. I'm not a developer so please forgive my naivety if this would get caught up in the same GT4 issue as for artist search would.

**Comment by SoongNoonien** [comment]
I don't think that this simplifies anything. Search for the initial letters is as hard as search for whole artists.

But to clarify: You are currently using the initial letter markers and they are useful on collections as large as yours? I would imagine that while scroll through such a long list one could easily spot the initial letters even without the explicit markers. On my collection there are letters where there is just one artist starting with this letter, therefore while scrolling it is possible to overlook it. One large collections this shouldn't happen that often, I guess.

**Comment by Richjn** [comment]
I don't find the initial latter markers useful for the reasons you mention but I can imagine they would be useful for others with smaller collections.

**Comment by SoongNoonien** [comment]
> I don't find the initial latter markers useful for the reasons you mention...

Ok, so I think I can remove them for now to fix this bug. Maybe in the future they fix the issue in GTK and the letter markers could be reintroduced if needed.

> ...but I can imagine they would be useful for others with smaller collections.

Yes, me too this is why I added them in the first place ;-) Ideally it will be possible sometime to search for artists which should cover this use case.

**Comment by Richjn** [comment]
Just wondering if there is much point to the artists list at all currently whilst there is no solution to searching in GTK4 ?

In testing I can get to "The Beatles" faster by searching for a track by The Beatles then click the album cover to take me to all of their albums than by scrolling the artists column. Removing the artists column would free up some valuable realestate.

I think if this were done we would then need a landing page to inform users they need to use the search function to get started.

Probably a bit of a radical suggestion but in my usage scenario it would make some sense.

**Comment by SoongNoonien** [comment]
> Just wondering if there is much point to the artists list at all currently whilst there is no solution to searching in GTK4 ?

Yes, there is, I'm using it almost exclusively :-) The searching problem is not necessarily GTK4's fault, ideally MPD would provide a way to make a case-insensitive artist search. I could (vary naively) implement an artist search without MPD using GTK4 or rather mostly built-in python abilities but it may be to slow for large collections. This would simply iterate over the artist list and check if each artist matches the search. I would cap the number of results much like for the songs but in the worst case the whole list has to be iterated. But it could be fast enough, maybe I'll get around to test this.

In current master the letter markers are gone. Is the scrolling issue gone now for you as well @Richjn?

**Comment by SoongNoonien** [comment]
> Yes, scrolling issue appears to be resolved here, however, I use a traditional mouse which was less sensitive to the issue anyway.

Ok, good. But what about using the scrollbar? Wasn't there the biggest problem on your setup?

> Would be good to get feedback from users with touchpads.

@rien333 already confirmed that it works with touchpads https://github.com/SoongNoonien/mpdevil/issues/88#issuecomment-1904939781.

> On the artists search front I wouldn't want to "spoil" the user experience for all by implementing something just for those with large collections. I wonder how many artists the average user has and at what point scrolling the list becomes painful. I will do a trial incrementing 500 artists at a time.... of course my results will be very subjective.

Ok, but at this point I think we should head back over to #86 to discuss the artist search.

**Comment by Richjn** [comment]
> Ok, good. But what about using the scrollbar? Wasn't there the biggest problem on your setup?

Ah yes, sorry.

Unfortunately the issue remains when dragging the scrollbar. I have swapped back & forth between the commit that removed the markers and things are slightly better with them removed but fundamentally scrolling is still jerky, not so with the mouse though even with the mouse scroll wheel set to it's fastest setting..... weird!

**Comment by SoongNoonien** [comment]
> Unfortunately the issue remains when dragging the scrollbar. I have swapped back & forth between the commit that removed the markers and things are slightly better with them removed but fundamentally scrolling is still jerky, not so with the mouse though even with the mouse scroll wheel set to it's fastest setting..... weird!

This is weird indeed... I thought they fixed this problem. Unfortunately I can't do more to improve the situation here.
