### ISSUE TITLE
Stuck while autogenerating

### ISSUE THREAD

**Issue by DagBjorndal** [SoongNoonien/mpdevil#9]
I'm a newbie in Python - please forgive me. This is what I get running autogen.sh:

: 
checking for gtk 3.0 installed... not found
configure: error: required gtk version not found

I was expecting "sudo apt -y install libgtk-3-dev" to do the trick, but no. 

Can you please help me?

**Comment by SoongNoonien** [comment]
This is the complete list of packages needed on dpkg based distros: `dconf-gsettings-backend | gsettings-backend, python3, python3-mpd, python3-bs4, python3-requests, python3-gi, gir1.2-gtk-3.0, gir1.2-notify-0.7, python3-dbus`.
If you don't need the current version of git master I recommend you to use the .deb packages (they will automatically install all needed packages) You can download version 0.8.4 here: https://github.com/SoongNoonien/mpdevil/releases/download/v0.8.4/mpdevil_0.8.4-1_amd64.deb and older versions here: https://github.com/SoongNoonien/mpdevil/releases.

**Comment by DagBjorndal** [comment]
Thank you for your prompt answer. 

I'm using Raspberry Pi OS on Raspberry Pi 4 B, so I don't think I can use the .deb because of different architecture. 

All the packages you list (_dconf-gsettings-backend_, not _gsettings-backend_) are installed on my system "using sudo apt -y install _package_", but the error persist.

**Comment by SoongNoonien** [comment]
I'm not very familiar with Raspberry Pi OS, which is the default python version there? It may be necessary to specify the correct python version like for example:  `PYTHON=python3.6 ./autogen.sh`. The test performed by autogen is just importing gtk. If the gtk module is not available from the default python version the test will fail. You could try the test manually to see if there is more helpful output. Just run these three lines in the python interpreter: 
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
```

**Comment by DagBjorndal** [comment]
Raspberry Pi OS has both Python 2.7 and Python 3.7 installed - 2.7 is default. I changed this to 3.7 with _sudo update-alternatives install_. But this was not enough:

It seems the _gi_ package is called _pgi_ in this linux distribution, and so required me to install it with _pip3 install pgi_.

MPDevil runs now. Thank you very much!
