### ISSUE TITLE
Artist List where Artist is just one alpha

### ISSUE THREAD

**Issue by Richjn** [SoongNoonien/mpdevil#90]
Hi
I hesitate to call this a bug as it's such a corner case and may well not be worth looking at.

Using git Master
When browsing artists from the left of the browser window an artist that is just one alpha will appear above the separator for that alpha.
I have attached a screenshot showing "E"
![Artist_List](https://github.com/SoongNoonien/mpdevil/assets/117611987/fcb294b7-f510-4e35-96c5-60a753872c35)

**Comment by SoongNoonien** [comment]
Hi!
The newest commit should fix this.

**Comment by Richjn** [comment]
Hi
Confirm commit fixes the issue.
Thanks
