### ISSUE TITLE
Server statistics are wrong when mounting a networked storage through `mpd`

### ISSUE THREAD

**Issue by rien333** [SoongNoonien/mpdevil#96]
My local library contains 804 artists. However, mpd also [allows you to mount NFS shares](https://mpd.readthedocs.io/en/latest/protocol.html#mounts-and-neighbors), which are then treated as any other part of your library (to test, run something like `mpc mount music nfs://domain.local/srv/nfs/music`). In my case, that NFS share contains less artist, probably 400 or so. 

I've noticed that mpdevil's server statistics are wrong when mpd has mounted an NFS share. Specifically, it seems that mpdevil only reports the statistics about my network share, rather than my local library + network share.

**Comment by SoongNoonien** [comment]
I'm just using the `stats` command of MPD to fill the server statistics window. What is reported with `mpc stats`?

**Comment by rien333** [comment]
> What is reported with mpc stats

Weird, the output correct now. Closing until I find a reliable reproducer.
