### ISSUE TITLE
Artist list does not restore previous position and fails to render completely 

### ISSUE THREAD

**Issue by rien333** [SoongNoonien/mpdevil#97]
I'm seeing two issues related to the artist list, both of which I've bisected to https://github.com/SoongNoonien/mpdevil/commit/f0ba8360dc790a229fb882f5ad2be6f00df8e68f.

# Expected behavior  

Running from https://github.com/SoongNoonien/mpdevil/commit/6583b4b06cabffed6ffdc2953b506f70096fd72a, mpdevil correctly restores its previous state, and renders my complete library in the left side pane: 

[Screencast from 2024-03-02 16-47-47.webm](https://github.com/SoongNoonien/mpdevil/assets/10417027/e9857cb0-0bd1-4025-92b8-a9422bd8e68d)

# Current behavior

Running from the  commit after that (https://github.com/SoongNoonien/mpdevil/commit/f0ba8360dc790a229fb882f5ad2be6f00df8e68f) , however, and mpdevil (1) fails to restore its state (doesn't scroll to the correct position),  and (2) renders only the first artist in the artist  pane. 

[Screencast from 2024-03-02 16-50-33.webm](https://github.com/SoongNoonien/mpdevil/assets/10417027/75cf1a19-138a-4756-bedc-a0ca27408090)

In order to reproduce (2), you need a fairly large library. For example I cannot  reproduce  with ~15 artist, but can consistently do so with 800 artists. Note also that everything starts rendering fine after performing a scrolling action. 

---

May be more of a GTK issue? Some of this sounds similar to https://github.com/SoongNoonien/mpdevil/issues/88

**Comment by SoongNoonien** [comment]
Yes, this is a GTK bug. On my machine I only have the scrolling problem while the list renders fine. Note that the playlist is affected as well. I've reported the scrolling bug https://gitlab.gnome.org/GNOME/gtk/-/issues/6501. But I think I can work around this, I'm working on it.

**Comment by SoongNoonien** [comment]
At least over here a47b1aa fixes the scrolling issue. What about the rendering problem, is it fixed too?

**Comment by rien333** [comment]
> What about the rendering problem, is it fixed too?

Yes!
